from pathlib import Path
import sys, json, itertools, collections, math
from datetime import datetime
from zoneinfo import ZoneInfo
import numpy as np
sys.path.insert(0,'/tmp/r5_analysis')
from tables import *
ROOT=Path('/home/weiland/projects/openpi'); CL=Path('/home/weiland/trace_runs/os_closed_loop')
OUT=ROOT/'exp/offline_search/rounds/r05/ANALYSIS.md'
parts=[]
def put(s):parts.append(s.strip()+'\n\n')
def table(headers,rows):
 put('| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+'\n'.join('| '+' | '.join(str(c) for c in r)+' |' for r in rows))
def sr(l):return f"{A[l]['sr']:.3f}"
def ir(l):return f"{A[l]['ir']:.5f}"
def point(l):return sr(l)+' @ '+ir(l)
def mb(l):return '—' if A[l].get('fit_bytes') is None else f"{A[l]['fit_bytes']/1e6:.3f}"
def poolcost(ls):return sum(A[l]['N']*A[l]['ir'] for l in ls)/sum(A[l]['N'] for l in ls)
def poolstat(n):
 p=P[n];return f"{pp(p['delta'])} pp, 95% CI {ci(p['ci'])}"
def g(s,n,kind):
 ss='l10' if s=='l10' else 'spatial'
 return {'one':f'r5x_g_{s}_{n}_tail1u','two':f'gb_{s}_{n}_tail2u','mix':f'r5q2_g_{ss}_{n}_G10','inf':f'r5q2_g_{ss}_policy_L10'}[kind]
def q6(s,n):return f'r5q6_p_{s if s=="l10" else "spatial"}_{n}_tail'
put('''# R5 analysis — offline action cache for π0.5 / GR00T N1.5 on LIBERO

Snapshot: **@SNAPSHOT@**, after both K7 replicates completed; the final four-run pool and the original planned three-run pool are now available. This report extends [R4](../r04/ANALYSIS.md), following [the R5 brief](ANALYSIS_BRIEF.md), [selection and both addenda](SELECTION.md), [findings](FINDINGS.md), [coding brief](CODING_BRIEF.md), ideation A–D reports, Q1–Q6 hand-backs, and [the coordinator ledger](../../../../logs/offline_search_exploration.log.md) §§8–10. Ledger outcome numbers were not used as computed results.

**Result:** longer cached commitments improve π0.5 in all four cells; GR00T needs suite-dependent commitment length and policy use. All four K7 repeats retain an advantage over three stock repeats; the completed prescribed three-run set also retains the same positive direction with an interval above zero. C10 lowers policy cost without establishing SR superiority; Q6 is promising under an assumed wrist cost model. Paid library growth and refitting help substantially. B1 does not validate its offline objective as a closed-loop SR selector. GPU shadow is faster at the median, but action parity remains incomplete.

Only completed arms with both a completion marker and a per-arm summary are used. Per the coordinator's clarification, `state/<arm>.manifest_<sha>.DONE` is a valid marker; the four grow250 saved manifests were checked against `q4_growth/evaluation_pairs.json`. **All 52 requested R5 arms are complete and included**, together with the R4 cell fill and historical references. Replicate B was admitted only after checking its DONE marker, per-arm summary and accepted journal pairs.

Provenance and conventions: let **R** = `/home/weiland/trace_runs/os_closed_loop`. An arm identified as `run/arm` always means `R/run/runs/arm/summary.json`, `R/run/runs/arm/client/journal.jsonl`, and its completion marker in `R/run/state/`. The source index in §9 maps every short alias. SR is success/accepted episodes, normally 500 = ten tasks × inits 0–49; grow250 uses 250 = ten tasks × inits 25–49. Accepted attempts were matched before reading server decisions. All @NARMS@ completed arms passed journal count, pair-identity, and summary-success checks. The raw-decision audit covered @NAUDIT@ arms / @NDECISIONS@ deduplicated accepted decisions, including all @NR5@ completed R5 arms; R5 had zero duplicate/conflicting decisions, discontinuous sequences, or `ok=false` decisions. One legacy R3 cost conflict is explicitly excluded from valid cost rankings (§9).

Reproduction from the repository root (CPU only; outputs stay in `/tmp/r5_analysis/` except this report):

```bash
taskset -c 26-29,70-73 env OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 CUDA_VISIBLE_DEVICES='' PYTHONDONTWRITEBYTECODE=1 .venv/bin/python /tmp/r5_analysis/analyze.py
taskset -c 26-29,70-73 env OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 CUDA_VISIBLE_DEVICES='' PYTHONDONTWRITEBYTECODE=1 .venv/bin/python /tmp/r5_analysis/audit_logs.py
taskset -c 26-29,70-73 env OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 CUDA_VISIBLE_DEVICES='' PYTHONDONTWRITEBYTECODE=1 .venv/bin/python /tmp/r5_analysis/write_report.py
```

`analysis.json` contains all arm counts/costs, @NPAIRS@ pair comparisons, pooled contrasts and source hashes; `journals.json` contains paired outcomes; `decisions.json` contains source paths, realized control counts, and shadow aggregates. The scripts read historical arm/K8 dictionaries using AST literals, without executing the R4 scripts. Analysis did not launch or alter any experiment.

Statistics: table contrasts are **A minus B**, in percentage points, followed by a 95% paired bootstrap interval, **W/L = A-only successes / B-only successes**, and exact two-sided McNemar p. Bootstraps use 10,000 draws, seed 20260928, resampling the `(task, init)` unit (R4's init convention), not individual decisions. Repeat comparisons average outcomes within each pair before resampling its entire repeat vector; thus four repeats still provide 500 clusters, not 2,000 independent initializations. This is conditional on these ten tasks and the observed run seeds; it does not estimate generalization to new tasks or fully integrate run-to-run uncertainty. Pooled B1 uses an equal-weight six-cell mean, stratifies resampling by suite (500 pair clusters in each of two suites), and keeps the outcomes for models and library scales together within each suite/task/init. Numeric task IDs in different suites are not treated as the same scene. Single-arm Wilson intervals and per-task success counts are in `analysis.json`. Unless specifically stated, p values are exploratory and unadjusted; non-significance is not equivalence.

Costs: owner IR is recomputed from each arm's `cost_ledger` counts, `v=V/N`, `m=M/N`: π0.5 `(.152 v + .848 m) × 5/L`; GR00T `(.148 v + .852 m) × 5/L`. L is controls/request: normally 5, or 10 for pure L=10 inference. A blind or policy-tail five-control slot incurs no new model inference. **Wrist ASSUMPTION:** `(.0552 v + (.848+.0499)m) × 5/L`, the R4 eager-to-owner ratio transfer, not an R5 graph measurement. Full-camera π0.5 dummy_cached repricing is the brief's stipulated exact `−.048 v × 5/L`; this is a counterfactual cost panel, not a newly measured R5 run. It is not stacked onto wrist or transferred to GR00T. Legacy R2/R3 summaries lack `cost_ledger`; their full-vision v=1 and m were reconstructed from counts and checked against raw decisions where possible. Summary eager/measured IR fields are not substituted for owner IR. Fit MB below means decimal serialized pickle MB, not resident memory or total deployment bytes.
''')
put('## 1. Noise floor and acceptance rule')
stock=['g500','g500_repa','g500_repb'];tails=['k7_tail1ug','r5b_p_l10_500_hand','r5x_p_l10_500_k7tail_repa','r5x_p_l10_500_k7tail_repb']
planned=['k7_tail1ug','r5x_p_l10_500_k7tail_repa','r5x_p_l10_500_k7tail_repb']
table(['Configuration / completed runs','SRs','Mean SR','Sample SD / range (pp)','Pooled decision-weighted owner IR'],[
 ['Stock g500',', '.join(sr(l) for l in stock),f'{np.mean([A[l]["sr"] for l in stock]):.5f}',f'{np.std([A[l]["sr"] for l in stock],ddof=1)*100:.3f} / {np.ptp([A[l]["sr"] for l in stock])*100:.2f}',f'{poolcost(stock):.5f}'],
 ['K7 tail: R4, B1 hand, replicates A/B',', '.join(sr(l) for l in tails),f'{np.mean([A[l]["sr"] for l in tails]):.5f}',f'{np.std([A[l]["sr"] for l in tails],ddof=1)*100:.3f} / {np.ptp([A[l]["sr"] for l in tails])*100:.2f}',f'{poolcost(tails):.5f}'],
 ['K7 prescribed: R4, replicates A/B',', '.join(sr(l) for l in planned),f'{np.mean([A[l]["sr"] for l in planned]):.5f}',f'{np.std([A[l]["sr"] for l in planned],ddof=1)*100:.3f} / {np.ptp([A[l]["sr"] for l in planned])*100:.2f}',f'{poolcost(planned):.5f}']])
table(['A − B','Paired ΔSR [95% CI]; W/L; exact p','Discordance'],[[f'`{a}` − `{b}`',stat(a,b),f'{pair(a,b)["discordant"]}/500 ({pair(a,b)["discordant"]/5:.1f}%)'] for ls in [stock,tails] for a,b in itertools.combinations(ls,2)])
put(f'''Identical configurations vary by about three SR points; even the stock .864 versus .832 repeat yields nominal p={pv(pair('g500','g500_repb')['p'])}. A single positive p<.05 is therefore insufficient grounds for accepting a small engineering gain. Retain R4's rule: use a paired comparison to the per-init mean of repeated references, require an interval above zero for an SR improvement, inspect repeat spread and task concentration, and repeat small effects before promotion. If preserving SR while saving cost is the claim, predeclare a noninferiority margin and test it; none was declared here. Spatial differences below one point require particular restraint.

The **four completed K7 runs** (R4 + B1 hand + replicates A/B) versus stock give **{poolstat('K7_all4_vs_stock3')}**. Owner IR falls from {poolcost(stock):.5f} to {poolcost(tails):.5f}, a computed {100*(1-poolcost(tails)/poolcost(stock)):.1f}% reduction. Thus the positive K7 effect survives the final four-run comparison, and is not dependent on selecting the best .906 run. Net paired gains are concentrated in tasks 8 and 9 ({P['K7_all4_vs_stock3']['per_task'][8]:.2f} and {P['K7_all4_vs_stock3']['per_task'][9]:.2f} mean additional successes across repeats); task 4 loses {-P['K7_all4_vs_stock3']['per_task'][4]:.2f}. This remains a conditional, benchmark-specific result.

The completed original planned set is **R4 + replicate A + replicate B**: mean SR {np.mean([A[l]['sr'] for l in planned]):.5f}, with **{poolstat('K7_planned3_vs_stock3')}** against stock. Both the prescribed three-run and all-four-run comparisons satisfy the paired interval-above-zero acceptance criterion. Adding the independently verified B1 hand repeat changes the point estimate but not that conclusion; neither interval fully integrates uncertainty over future run seeds.

Replicate B (`r05_x/r5x_p_l10_500_k7tail_repb`) independently yields {A[tails[-1]]['success']}/{A[tails[-1]]['n']} successes = {sr(tails[-1])}. Its per-arm ledger has N={A[tails[-1]]['N']}, V={A[tails[-1]]['V']}, M={A[tails[-1]]['M']}, hence v={A[tails[-1]]['v']:.8f}, m={A[tails[-1]]['m']:.8f}, owner IR={ir(tails[-1])}; the served fit is {A[tails[-1]]['fit_bytes']:,} bytes. Its accepted raw decisions match those counts. All nine within-configuration repeat comparisons are shown above; no individual run is selected as the configuration estimate.''')
put('## 2. Execution length on the cache and policy sides')
table(['π0.5 cell','CL2 L=5 SR @ owner IR','Pure-cache 10-step tail SR @ IR','Tail − CL2: Δ pp [CI]; W/L; p'],[[f'{s}-{n}',point(f'cl2_{s}_{n}'),point(pt(s,n)),stat(pt(s,n),f'cl2_{s}_{n}')] for s in ['l10','sp'] for n in [50,500]])
put('''All four cached-tail contrasts are positive; all survive Holm correction within this four-cell family (maximum adjusted p < .026). R5 extends R4's spatial-500 result to l10 and the 50 libraries. The three R5 pure-tail ledgers have **zero MISS**, so these gains cannot be purchased by additional policy calls. They retain an anchor every other five-control slot, with maximum blind run one. The comparison changes both reobservation cadence and commitment to the stored chunk's second half; it is a control/execution effect, not evidence that the visual or synthesis representation improved.

R4's policy result remains relevant: π0.5 l10 L=10 runs .904/.900 have mean .902 at IR .5; L=5 seeded runs .848/.860 have mean .854 at IR 1. Their paired pooled contrast is +4.80 pp [2.30, 7.20]. Historical trace_dual L=5 is .844 on l10 and .986 on spatial; spatial L=10 is also .986. R4 already established that longer policy execution can improve l10 while halving decisions. Do not attribute that component to cache retrieval. Trace_dual values are read from R4/brief and shown descriptively: **ASSUMPTION for this extension:** cross-harness L=5 traces are not treated as an independently verified paired execution-length experiment, particularly for GR00T.''')
table(['GR00T cell','CL2 L=5','Tail L=10 (one blind block)','Tail L=15 (two blind blocks)','Pure policy L=10','Historical policy L=5'],[[f'{s}-{n}',point(f'cl2_g_{s}_{n}'),point(g(s,n,'one')),point(g(s,n,'two')),point(g(s,n,'inf')),('.870 @ 1' if s=='l10' else '.940 @ 1')] for s in ['l10','sp'] for n in [50,500]])
table(['GR00T cell','10-step tail − CL2','10-step tail − 15-step tail','10-step tail − policy L=10','15-step tail − policy L=10'],[[f'{s}-{n}',stat(g(s,n,'one'),f'cl2_g_{s}_{n}'),stat(g(s,n,'one'),g(s,n,'two')),stat(g(s,n,'one'),g(s,n,'inf')),stat(g(s,n,'two'),g(s,n,'inf'))] for s in ['l10','sp'] for n in [50,500]])
put('''GR00T l10 favors cached commitment over fresh five-step retrieval (+5.6/+12.4 pp at 50/500); spatial does not (−2.0/−0.2 pp). Every 10-versus-15 tail SR difference is unresolved in one run, including the newly completed spatial-50 .868 versus .864. Fifteen-step tails cost about .050–.052; ten-step tails cost .074–.076, so the modest numerical preference for ten does not prove its extra vision is worthwhile. R4's spatial-500 phase rule remains .976 @ .07834, beating its 15-step tail by 3.0 pp (R4); it also exceeds the new policy L=10 by 3.8 pp, W/L 31/12, p=.0054, CI [1.4, 6.4]. Stored tail continuation and selecting a new phase successor are different control operations.

GR00T policy L=10 is .866 l10 / .938 spatial at IR .5 versus historical L=5 .870/.940. Those tiny descriptive changes cannot establish a causal length effect. The useful variable is **source × commitment length × suite/library**, not a universal “commit” switch. Keep mandatory vision anchors and the measured one-/two-block blind caps; the favorable π0.5 L=10 result does not justify unbounded GR00T continuation.''')
put('## 3. C10 policy commitment and D1 grasp checks')
table(['Cell','C10 SR @ owner IR','C10 − single R4 K7','C10 − pure policy L=10'],[[f'{s}-{n}',point(f'r5q1_c10_p_{s}_{n}'),stat(f'r5q1_c10_p_{s}_{n}',k7(s,n)),stat(f'r5q1_c10_p_{s}_{n}',f'inf_{s}_L10')] for s in ['l10','sp'] for n in [50,500]])
put(f'''For l10-500 the stronger comparator is repeated K7: C10 − four-run K7 mean is **{poolstat('r5q1_c10_p_l10_500_vs_K7_all4')}**; versus stock mean it is {poolstat('r5q1_c10_p_l10_500_vs_stock3')}. C10 reduces owner cost {100*(1-A['r5q1_c10_p_l10_500']['ir']/poolcost(tails)):.1f}% against pooled K7 but has a −2.00 pp point change and allows a −4.35 pp loss in the interval. This is a cost/SR trade, not demonstrated preservation or improvement. Against the prescribed three-run pool, C10 gives {poolstat('r5q1_c10_p_l10_500_vs_K7_planned3')}; the interpretation is unchanged.

Spatial-500 K7's B1 hand repeat gives mean SR .980; C10's .982 differs by +0.20 pp, CI [−1.00, +1.40] (inverting the saved pooled comparison). Pure-cache tail already reaches .982 at .07819, so C10's additional policy calls buy no observed SR there. At 50, C10 improves K7 numerically but neither cell resolves superiority. Against pure policy L=10, l10-50 and spatial-50 lose 7.4/7.6 pp; l10-500 loses 3.8 pp with exact p=.0558. Its bootstrap interval narrowly excludes zero while exact McNemar does not: use the prespecified exact test, not whichever yields significance. The second l10 L=10 reference .900 yields −3.4 pp, W/L 29/46, p=.0639. No equality claim follows.''')
table(['C10 cell','N / V / M','v / m','Policy-tail slots / N','MISS with follow-up → tail','Terminal MISS','Max blind run'],[[f'{s}-{n}',f"{A[l]['N']} / {A[l]['V']} / {A[l]['M']}",f"{A[l]['v']:.5f} / {A[l]['m']:.5f}",f"{D[l]['policy_tails']} / {A[l]['N']} = {100*D[l]['policy_tails']/A[l]['N']:.3f}%",f"{D[l]['tail_after_miss']}/{D[l]['miss_with_followup']}",D[l]['terminal_misses'],max(map(int,D[l]['blind_runs']))] for s in ['l10','sp'] for n in [50,500] for l in [f'r5q1_c10_p_{s}_{n}']])
put('''Every nonterminal C10 MISS is followed by its policy tail; terminal MISSes explain why policy-tail slots are fewer than MISSes, especially on short successful spatial episodes. The realized tail share is 2.5–12.0% of decisions, not 50%. Roughly half of all decisions are blind, mostly cache tails. Costs and SR therefore include both cached ten-step commitments and a smaller amount of ten-step policy execution. The lifecycle gate appears to be exercised as intended; it does not establish the causal value of each individual policy tail.''')
table(['D1 cell','SR @ owner IR','D1 − K7','Triggered episodes /500','Successful / failed triggered episodes','Trigger task counts (0…9)'],[[f'l10-{n}',point(l),stat(l,k7('l10',n)),len(D[l]['grasp']),f"{sum(x['success'] for x in D[l]['grasp'])} / {sum(not x['success'] for x in D[l]['grasp'])}",','.join(str(sum(int(x['uid'].split(':')[-2])==t for x in D[l]['grasp'])) for t in range(10))] for n in [50,500] for l in [f'r5q1_d1_p_l10_{n}']])
put(f'''Raw `look_reason=9` / `extras.grasp_check=1` rows show 84/24 checks at 50/500, at most one per episode, all vision-bearing MISSes. Q1's pre-intervention replay reach was 73/24 episodes ([hand-back](q1_commit/HANDBACK.md)); changed trajectories mean replay reach is not an invariant exposure count. Reach is limited, and task 4 has no triggers despite being a weak K7 task. Success after a check is not the check's treatment effect. D1-500 versus pooled K7 is {poolstat('r5q1_d1_p_l10_500_vs_K7_all4')}. **One run cannot resolve D1's small predicted effect** (Q1's ≈0.39 pp at 500); there is neither adoption evidence nor proof of zero benefit. The 50 result is also within the measured run noise.''')
put('## 4. GR00T CycleTail mixed mode')
table(['Cell','G10 SR @ owner IR','G10 − tail L=10','G10 − tail L=15','G10 − policy L=10'],[[f'{s}-{n}',point(g(s,n,'mix')),stat(g(s,n,'mix'),g(s,n,'one')),stat(g(s,n,'mix'),g(s,n,'two')),stat(g(s,n,'mix'),g(s,n,'inf'))] for s in ['l10','sp'] for n in [50,500]])
table(['Cell','N / V / M','v / m','MISS / vision anchors','Policy tails / decisions','Nonterminal MISS → tail / terminal MISS'],[[f'{s}-{n}',f"{A[l]['N']} / {A[l]['V']} / {A[l]['M']}",f"{A[l]['v']:.5f} / {A[l]['m']:.5f}",f"{100*A[l]['M']/A[l]['V']:.2f}%",f"{D[l]['policy_tails']} / {A[l]['N']} ({100*D[l]['policy_tails']/A[l]['N']:.2f}%)",f"{D[l]['tail_after_miss']}/{D[l]['miss_with_followup']} / {D[l]['terminal_misses']}"] for s in ['l10','sp'] for n in [50,500] for l in [g(s,n,'mix')]])
put('''G10 pays a scheduled policy call every fourth anchor, beginning with a paid anchor. Finite episode endings make the realized MISS share .130–.145, above the infinite-horizon .125 design value; 25.8–28.3% of anchors are paid. Every eligible policy tail is served and all observed blind runs have length one. This is GR00T mixed mode with actual policy cost, not a pure-cache length variant.

At **50**, policy calls buy +11.0 pp l10 and +5.2 pp spatial versus ten-step pure tails (p<.0001 / .0049), at IR .18503/.19794 instead of .07428/.07529. The two favorable 50-cell tests also survive Holm correction over the four G10-versus-ten-step-tail comparisons. G10 remains well below pure policy on l10-50; spatial-50's −1.8 pp versus policy is unresolved, not equivalent. At **500**, G10 is point-dominated by ten-step pure tail in both suites: l10 .828 @ .18605 versus .830 @ .07450, and spatial .952 @ .19897 versus .964 @ .07551. Spatial-500 phase is better still (.976 @ .07834). The result rejects a universal periodic policy schedule for large libraries, while supporting selective policy use with the smaller bank. It does not tell us which particular scheduled calls are useful.''')
put('## 5. Wrist plus tail (Q6) and the wrist spatial-50 repeat')
table(['Cell','Q6 SR @ wrist owner IR (ASSUMPTION)','Q6 IR if charged full-camera owner prices','Q6 − K7','Q6 − R4 wrist guard-only'],[[f'{s}-{n}',point(q6(s,n)),f"{A[q6(s,n)]['ir_full']:.5f}",stat(q6(s,n),k7(s,n)),stat(q6(s,n),f'wrist_{s}_{n}')] for s in ['l10','sp'] for n in [50,500]])
put(f'''Q6 combines wrist-confirmed stuck guards, a wrist visual key, and cached ten-step tails. At l10-500, .892 @ .16209 versus four-run K7 {np.mean([A[l]['sr'] for l in tails]):.5f} @ {poolcost(tails):.5f} gives **{poolstat('r5q6_p_l10_500_tail_vs_K7_all4')}** and {100*(1-A[q6('l10',500)]['ir']/poolcost(tails)):.1f}% lower assumed cost. Versus stock repeats it is {poolstat('r5q6_p_l10_500_tail_vs_stock3')}. This makes Q6 a promising cost candidate, but one run cannot establish its small advantage over K7 or preservation of pure-policy L=10 SR (−1.2 pp, W/L 38/44, p=.5811, CI [−4.8,+2.4]). If wrist is charged as full-camera inference, its l10-500 IR is .21066 and the claimed cost edge over K7 disappears. Measuring the wrist graph price is therefore material. Against the prescribed three-run pool, Q6 gives {poolstat('r5q6_p_l10_500_tail_vs_K7_planned3')}; it also fails to resolve an SR improvement.

At l10-50, Q6 .792 @ .19853 is point-dominated by C10 .830 @ .18073. Tail addition to wrist guard-only helps l10 (+5.8/+7.2 pp), but does not establish an improvement on spatial; spatial-50 actually drops 2.2 pp. Spatial-500 Q6 is .990 @ .07419, versus pure tail .982 @ .07819: +0.8 pp, W/L 7/3, p=.3438. Versus two pooled K7 runs it is {poolstat('Q6_sp500_vs_K7_available2')}. Its appealing raw frontier point is conditional on the wrist cost assumption and single-run SR, not a confirmed new accuracy record.

The independent wrist guard-only spatial-50 repeat is **.928 @ .15539** versus R4 .924 @ .15612. Repeat − R4 is {stat('r5t_p_sp_g50_wrist_rep','wrist_sp_50')}; repeat − stock .888 is {stat('r5t_p_sp_g50_wrist_rep','sp_g50')}. The two wrist runs average **.926**, with pooled difference from the shared stock run **{poolstat('wrist_sp50_available2_vs_stock')}** and owner IR {poolcost(['wrist_sp_50','r5t_p_sp_g50_wrist_rep']):.5f}. This reproduces the direction and size of R4's wrist result; the common one-run stock comparator remains a limitation. The natural spatial-50 wrist choice is guard-only, not automatically the Q6 stack.''')
put('## 6. Paid library growth and the demo-data curve')
put('''**Grow250 uses a separate held-out manifest.** Acquisition is ten tasks × inits 0–24; evaluation is ten tasks × inits 25–49. Every comparison below intersects the reference with those same 250 pairs. Both grown variants use ordinary CL2, five controls/request, zero MISS and no blind tails; they are compared with CL2 references, not with the demo-tail arms. Static-50 and grow250 use kref=5; static-500 uses kref=8, so the latter is not a candidate-count-only comparison. This follows the Q4 [hand-back](q4_growth/HANDBACK.md), `evaluation_pairs.json`, and the run's saved manifests/specs.''')
table(['Suite / variant','SR on 250 pairs','Serving IR','vs CL2-50 on same pairs','vs CL2-500 on same pairs','Refit − frozen'],[[f'{s} / {v}',sr(l),ir(l),stat(l,f'cl2_{s}_50'),stat(l,f'cl2_{s}_500'),stat(l,f'r5q4_p_{s}_grow250_frozen') if v=='refit' else '—'] for s in ['l10','sp'] for v in ['refit','frozen'] for l in [f'r5q4_p_{s}_grow250_{v}']])
put('''The reference SRs on this manifest are l10 **.600 / .756**, spatial **.772 / .964** for CL2-50 / CL2-500. Grown refit reaches .744/.952: both are 1.2 pp below static-500, with intervals [−7.2,+4.8] and [−4.4,+2.0]. Thus growth closes 92.3%/93.75% of the observed static-50→500 gap, but the data do not establish equality. Frozen append improves SR too; refitting adds 6.0 pp l10 (p=.0444) and 7.6 pp spatial (p=.0019). Both refit-versus-frozen tests survive Holm correction over these two comparisons (adjusted p=.0444 l10 / .0038 spatial), although the l10 increment is close to the noise boundary; the large gains over static-50 are much clearer. One acquisition split cannot establish generality, and the reverse split / GR00T growth were not run.''')
table(['Suite','Initial episodes / rows','Paid episodes / successful admissions','Policy calls paid','Appended / total rows','Final stored episodes','Raw store bytes per copy'],[
 ['l10','50 / 2,640','250 / 208','14,849','10,481 / 13,121','258','3,459,476,787'],
 ['spatial','49 / 1,018','250 / 248','5,310','5,222 / 6,240','297','1,645,435,050']])
table(['Suite / fit','Fit bytes','Evaluation decisions N','Acquisition + serving numerator','Lifecycle IR'],[[f'{s} / {v}',A[l]['fit_bytes'],A[l]['N'],f"{acq} + .152 × {A[l]['N']}",f"{(acq+.152*A[l]['N'])/(acq+A[l]['N']):.5f}"] for s,acq in [('l10',14849),('sp',5310)] for v in ['refit','frozen'] for l in [f'r5q4_p_{s}_grow250_{v}']])
put('''Acquisition counts/rows/raw-store bytes are read from Q4's published provenance and hand-back; fit sizes above are independently `stat`-read. All 250 paid episodes count toward acquisition, including failures; only successful rows enter the bank. Exact duplicate admissions were zero. The nominal spatial-50 base actually contains 49 episodes. Refitting uses all grown candidates; frozen append preserves the original representation, scales and calibration. This separates candidate coverage from refitting better than a simple 50→500 comparison, though it is not a factorial decomposition of every fit component.

**Lifecycle ASSUMPTION:** price an acquisition policy call as 1 and an evaluation CL2 five-control decision as .152, then normalize by the same number of nominal full-policy decision slots: `(A + .152 N)/(A+N)`. These are 250 acquisition + 250 evaluation episodes with their actual decision counts, not equal-length synthetic episodes. Refit's lifecycle IR is .55695 l10 / .57279 spatial; frozen is .54722/.55462. Longer, less successful evaluations can lower this ratio mechanically, so it is not a total cost-to-success metric. Absolute normalized work is A+.152N in the table, and initial demo acquisition is unpriced for all candidates. Serving-only .152 is a steady-state accounting boundary, not a free-data claim; acquisition amortizes only over later deployment traffic. Raw grow stores need 5,104,911,837 bytes per disk/RAM copy in addition to the compact fits.''')
rows_demo={'l10':{50:2640,100:5764,200:11718,300:17612,500:29472},'sp':{50:1018,100:2257,200:4440,300:6577,500:10909}}
def demo(s,n):return pt(s,n) if n in [50,500] else f'r5q4d_p_{s}_{n}_refit_tail1'
table(['Suite / nominal episodes','Controller / kref','Rows','SR','v / m','Owner IR','Fit bytes'],[[f'{s} / {n}','anchor_tail / '+('8' if n==500 else '5'),rows_demo[s][n],sr(l),f"{A[l]['v']:.5f} / {A[l]['m']:.5f}",ir(l),A[l]['fit_bytes']] for s in ['l10','sp'] for n in [50,100,200,300,500] for l in [demo(s,n)]])
table(['Suite / contrast','SR refit / frozen200','Rows (both)','Frozen200 owner IR','Frozen200 fit bytes','Paired Δ pp [CI]; W/L; p'],[[s,f"{sr(demo(s,200))} / {sr(f'r5q4d_p_{s}_200_frozen50_tail1')}",rows_demo[s][200],ir(f'r5q4d_p_{s}_200_frozen50_tail1'),A[f'r5q4d_p_{s}_200_frozen50_tail1']['fit_bytes'],stat(demo(s,200),f'r5q4d_p_{s}_200_frozen50_tail1')] for s in ['l10','sp']])
table(['Suite','100 − 50','200 − 100','300 − 200','500 − 300'],[[s]+[stat(demo(s,a),demo(s,b)) for a,b in [(100,50),(200,100),(300,200),(500,300)]] for s in ['l10','sp']])
put('''The demo curve holds the pure-cache tail controller fixed and has zero MISS throughout. It is **not the paid grow250 curve**. The 100/200/300 demo subsets are nested within the 500 B-pool; the current 50 library is a different source and has no source-path/row/hash overlap with those subsets (Q4 hand-back). The 500 endpoint also changes kref from 5 to 8. B1's null result does not establish these kref settings are equivalent. Do not infer a clean marginal value of the first 50→100 or the last 300→500 demonstrations.

Refit l10 progresses .706→.748→.788→.806→.828. Spatial is .838→.950→.970→.944→.982: the 300 point is lower than 200 by 2.6 pp, p=.0533, and the paired bootstrap interval [−5.0,−0.2] illustrates another exact-test/interval boundary disagreement. This is not a proven monotone curve or proven saturation. Spatial-200 versus 500 is −1.2 pp (W/L 8/14, p=.2863, CI [−3.0,+0.6]); it is a plausible smaller bank, not demonstrated equivalent. At 200, refitting rather than projecting through frozen50 changes l10 .684→.788 (+10.4 pp) and spatial .808→.970 (+16.2 pp), both p<.0001. Additional candidates alone do not capture most of the possible benefit; fit geometry matters.

Rows are read from Q4's demo-curve metadata/hand-back; pickle sizes are from the exact served artifacts in the §9 source index. The 50→500 π0.5 tail fits are 26.091→95.265 MB l10 and 21.910→47.409 MB spatial. Compact representation accounting is approximately 580 B/row for AWM, 586 for BlindAWM, 632 for K7/C10, 370 for wrist guard-only, and 376 for Q6; D1 adds nine bytes/row to its K7 base. These summary representation counts are not the full pickle divided by row count. Two-camera PCA bases alone take 17,039,360 bytes (R4); action payloads of 280 B/π0.5 row or 448 B/GR00T row are already in the artifacts, with padded 32-column storage. GR00T has 2,645/29,631 l10 and 1,063/11,751 spatial rows at 50/500. Growth fits are .0526/.0351 GB while the full raw stores are 3.459/1.645 GB per copy; deployment must distinguish these storage boundaries.

Deployment recommendation: prefer a periodic refit after acquiring a material batch, keep acquisition outside evaluation, and retain raw provenance if future refits are required. When policy data are purchased, report its amortization separately. Where only 50 episodes are available, use the measured 50-cell controller choices in §9 instead of importing a 500-library metric. Spatial-200 is a candidate memory compromise for a later noninferiority test; l10 still shows a useful library-size trend. No online append speed, GPU-resident growth, opposite-fold result, or zero-cost acquisition is established.''')
put('## 7. B1: offline solver versus hand settings')
choices=json.loads((ROOT/'exp/offline_search/rounds/r05/ideation_B/solver_choices.json').read_text())
choice_map={(('p' if x['cell'].startswith('pi') else 'g'),('l10' if 'l10' in x['cell'] else 'sp'),x['scale']):x for x in choices}
changes={('p','sp',50):'ridge_main .1 → 1',('p','sp',500):'kref 8 → 5',('p','l10',500):'kref 8 → 5',('g','sp',50):'ridge_main .1 → 1',('g','sp',500):'state_scale 1 → 3',('g','l10',500):'state_scale 1 → 3'}
table(['Cell','One changed parameter','Hand SR @ IR','Solve SR @ IR','Solve − hand','Offline LOTO action / state RMS Δ'],[[f'{m}-{s}-{n}',changes[m,s,n],point(h),point(l),stat(l,h),f"{c['LOTO_mean_delta']['action_RMS']:+.6f} / {c['LOTO_mean_delta']['state_RMS']:+.6f}"] for m,s,n in changes for l,h,c in [(f'r5b_{m}_{s}_{n}_solve',f'r5b_{m}_{s}_{n}_hand',choice_map[m,s,n])]])
table(['Equal-weight paired pool','Solve mean SR','Hand mean SR','Δ pp [95% clustered CI]'],[[m,f"{P['B1_'+m]['srA']:.5f}",f"{P['B1_'+m]['srB']:.5f}",poolstat('B1_'+m)] for m in ['p','g','all']])
put('''The frozen offline objective predicts improvement in all six cells (lower action and successor RMS); closed-loop SR rises in only two of six, and no per-cell McNemar test is significant. The all-cell mean and suite-stratified interval are given in the pooled table. That pooled estimand weights each tested cell equally; it is not a pooled six-task deployment or six independent confirmations. The prospective test rejects the claim that these score improvements reliably rank closed-loop SR. It does not prove that every offline selection method is impossible, nor that the tested parameters have no effect.

Configuration checks use `r05_b1/arms_in.json` and `arms.json`, compared with reference specs. π0.5 l10-500 and spatial-500 hand are K7 tail repeats; GR00T l10-500 and spatial-500 hand are R2 CL2 repeats. Those are pooled in §1/§9 rather than cherry-picking B1 hand .906 as the K7 estimate. At spatial-50 the B1 hand and solve use the explicit ridge-capable AWM3 implementation; the paired intervention is clean inside B1, but equality to the original historical fit/tie handling has not been independently proved here. **ASSUMPTION:** do not pool spatial-50 B1 hand with the older implementation as a certified repeat. R5's K7 spatial-50 .894 remains the direct R4-cell fill. This conservative qualification does not change B1's six paired results.

Offline values above are read from `ideation_B/solver_choices.json`, not invented SR predictions. The proxy is conditional LOEO/LOTO in a library-fitted representation, not a fully inductive train-on-nine-tasks / evaluate-on-unseen-task pipeline. Ideation B's normalization audit and frozen candidate choices constrain leakage; action-unit conventions for the large library remain inherited and must be labeled, and no 50 fit is credited with 500-library statistics. Lower recorded-action error and successor error do not observe the controller's changed rollout distribution, rescue value or execution-length dynamics.

**Direct answer to the owner:** the selected finite parameter grid can be solved offline for its declared proxy, but **R4 + R5 do not support solving deployment SR by that proxy alone**. R4's tail/phase and noprog misrankings, unresolved K5 geometry-to-call-value mapping, and R5's six prospective cells are consistent with a missing control/outcome objective. RIT/LDA's solvable fit does not supply that objective automatically. Keep the hand defaults where the only justification for a replacement is lower proxy loss; use B1 as falsification evidence and avoid another retrospective winner search. A later owner-approved solver study should preregister one objective, establish inductive split/normalization rules, and validate rankings on fresh repeated rollouts.''')
put(f'''As a secondary final-repeat check, l10-500 B1 solve versus the four-run K7 hand configuration gives {poolstat('r5b_p_l10_500_solve_vs_K7_all4')}; the pure-cache tail versus that same pool gives {poolstat('r5t_p_l10_500_tail1uc_vs_K7_all4')}. This does not replace B1's prespecified one-to-one solve/hand contrast above.''')
put('## 8. Q5 live GPU retrieval shadow')
put('''Both arms are pure CL2 and serve CPU actions. This is live shadow measurement under load, not GPU-served SR and not the earlier stored-query microbenchmark. Raw sources are `R/r05_q5/runs/<arm>/server_*/decisions_*.jsonl`, restricted to each journal's accepted attempt. The audit also aggregates all raw shadow rows; accepted counts below are the relevant rollout cohort. Chunk tolerance is 1e-4 and confidence tolerance 1e-3, as specified by Q5.''')
gpu={n:D[f'r5q5_p_l10_{n}_cl2_shadow']['gpu_accepted'] for n in [50,500]}
table(['Metric','50 (35,750 decisions)','500 (31,835 decisions)'],[[key]+[f"{gpu[n][key]['count']}/{gpu[n]['n']} ({gpu[n][key]['fraction']*100:.5f}%)" for n in [50,500]] for key in ['top1_agree','top16_set_agree','top16_order_agree','chunk_agree','confidence_agree']]+[
 ['Failed decisions',gpu[50]['failed'],gpu[500]['failed']],
 ['Step-zero / later chunk mismatches',f"{gpu[50]['chunk_mismatch_step0']} / {gpu[50]['chunk_mismatch_later']}",f"{gpu[500]['chunk_mismatch_step0']} / {gpu[500]['chunk_mismatch_later']}"],
 ['Max chunk error',f"{gpu[50]['chunk_max_abs']['max']:.10f}",f"{gpu[500]['chunk_max_abs']['max']:.10f}"],
 ['Max non-step-zero chunk error',f"{gpu[50]['later_chunk_max']:.10f}",f"{gpu[500]['later_chunk_max']:.10f}"],
 ['Max confidence error',f"{gpu[50]['confidence_abs']['max']:.8f}",f"{gpu[500]['confidence_abs']['max']:.8f}"]])
table(['Latency metric (ms)','50 p50 / p90 / max','500 p50 / p90 / max'],[[label]+[' / '.join(f'{gpu[n][key][q]:.3f}' for q in ['p50','p90','max']) for n in [50,500]] for key,label in [('event_ms','GPU retrieval event'),('wall_ms','GPU retrieval wall incl. final copy'),('gpu_path_event_ms','Pooling-to-GPU-retrieval event'),('cpu_query_ms','CPU method/query'),('cpu_path_ms','CPU complete recorded path')]])
table(['Shadow arm','SR @ owner IR','Shadow − R2 CL2'],[[f'l10-{n}',point(f'r5q5_p_l10_{n}_cl2_shadow'),stat(f'r5q5_p_l10_{n}_cl2_shadow',f'cl2_l10_{n}')] for n in [50,500]])
put('''The .644/.756 shadow SRs differ from CL2 .630/.768 by +1.4/−1.2 pp, both well inside observed run noise. The shadow action contract predicts the same action source, not identical realized success in a nondeterministic evaluation; neither exact test establishes an SR difference, and no formal equivalence margin was tested. Both owner IRs remain .152. Extra shadow work is a measurement overhead outside that model-inference ledger; do not claim that running both paths accelerates the robot.

The live **500-library post-initialization exception is material**: task 8, init 45, accepted attempt 1, step 46 (`r5q5_p_l10_500_cl2_shadow:eval:8:45`) has chunk error .0062419772 and confidence error .0132845941. Top-1 is 22292 on both paths, but the top-16 set/order differ. The stored-query hand-back had no such later chunk failure. A step-zero-only CPU fallback therefore does not close the live parity gap. Numerical cause is not established by this analysis; candidate boundary/tie behavior and action synthesis need investigation using this exact row.

GPU median wall query time is 2.873/3.700 ms versus CPU query 5.073/8.123 ms; the corresponding pooling-to-retrieval event medians are 4.415/5.456 ms versus CPU path 9.123/12.599 ms. Event and wall scopes differ and these are marginal quantiles under shared load, not sums or paired end-to-end speedups. Maximum GPU wall latency reaches 31.450/42.482 ms. Actual live timings are larger than the offline microbenchmarks, so §9's K8 surcharge and this live latency table must stay distinct.

Before promoting `serve`, resolve or explicitly contain **all** strict action/confidence mismatches, reproduce the live boundary case, define matching numerical/tie rules and a fallback policy, and have the coordinator run a paired GPU-served evaluation with measured end-to-end latency. Q5 currently implements a separate retrieval graph, not retrieval fused into the stage-1 graph; K7 blind guards, Q6 wrist and GR00T do not inherit this validation. No such follow-up is launched here. Q5 [hand-back](q5_gpu/HANDBACK.md) reports AWM GPU resident arrays 52,841,036 / 204,780,236 bytes, while fit pickles are 24,631,208 / 94,143,229 bytes and the native 1,103,155,631-byte preload is retained. A fast compact retrieval representation is not yet a reduced total-memory deployment.''')
put('''The subsequent [K8 idle re-check](../r04/k8_search_latency/IDLE_RECHECK.md) reproduced single-process CPU search p50 of approximately **1.1–2.2 ms**, supporting K8's method-cost table. Live serving with **24 connections per server** instead measured CPU search **3–6× slower**, while GPU retrieval event p50 was approximately **2.0–2.7 ms**. The source attributes the CPU gap to GIL/thread contention; these concurrency-dependent serving costs must remain distinct from single-process method costs and from GPU wall latency including copies. This qualification changes latency interpretation, not the owner inference ledger.''')
put('## 9. Eight-cell frontiers, search cost, repricing, and deployable bytes')
put('''Tables below include every completed R4/R5 point in the inherited R4 arm inventory, together with its R2/R3 references. Growth/demo points are in §6 because they use different library sizes and, for grow250, a different pair manifest; mixing those into a 50/500 frontier would violate the comparison. K2 and randomized K5 points are listed separately below. Repeats and shadow observations remain visible in the raw tables; the deployment assessment then pools certified repeats.

**F** = nondominated observed point, **D** = another point has no greater cost and no lower SR, with at least one strict inequality. This is a point-estimate Pareto label, not statistical superiority. **A** = wrist-price assumption; **U** = unverified legacy cost, excluded from dominance; **H** = descriptive historical trace; **P** = proxy search measurement for an unbenchmarked R5 variant. Dominance is recomputed separately for owner (**O**), owner+search (**S**), and dummy_cached (**d**). A dash is an unavailable cost, not zero. Searchless pure inference has surcharge zero. Very close frontier memberships can be noise or artifact-timing differences; §1's repeat rule overrides a raw winner.

**Search panel:** K8's per-vision/per-blind CPU p50 query times are inherited from `/home/weiland/.claude/jobs/a607dd74/tmp/analysis_r04/an.py`'s `K8` table and the [K8 report](../r04/k8_search_latency/REPORT.md), not measured again here. Charge `(q_v v + q_b(1−v)) × 5/L` ms per five controls. The table uses R4's common 67.5-ms denominator for continuity: `IR_S = IR_owner + query_ms/67.5`. For π0.5 this is its owner full-inference reference; **for GR00T it is only a common-π-time surcharge proxy, not GR00T-native total IR**. A separate GR00T-native panel below uses 41.441827491 ms, the sum of `stage1_ms`, `stage2_ms`, and `stage3_full_loop_ms` in `exp/libero_groot/config/rit/cost_groot_libero_measured.json`. Stage owner coefficients stay as mandated. R5 C10/G10/Q6/B1 and one-block tails reuse the nearest K8 parent query costs; these exclude any unmeasured wrapper overhead. The exact q values used are included in the source index. Q5 live latencies remain §8; no GPU improvement is credited to other methods.

**Dummy panel:** full-camera π0.5 receives the stipulated −.048v×5/L only. Wrist and GR00T are held at owner prices with no claimed compatibility. The pure π0.5 tail moves to roughly .0523–.0535, and pure L=10 policy to .476. Thus dummy_cached makes the full-camera pure-cache spatial-500 tail cheaper than Q6 and restores that low-cost alternative to the frontier. No unmeasured joint wrist+dummy discount is invented.''')
OK={l:r for l,r in A.items() if r['status']=='OK'}
def prices(r):
 search=r.get('search_ir')
 if r['family'].startswith('pure_inf'):search=r['ir']
 return {'O':r['ir'],'S':search,'d':r['dummy_ir']}
def pareto(rs,basis):
 valid=[(l,r) for l,r in rs.items() if l!='sp_awm_h50_50' and prices(r)[basis] is not None]
 return {l:('D' if any(prices(q)[basis]<=prices(r)[basis]+1e-12 and q['sr']>=r['sr']-1e-12 and (prices(q)[basis]<prices(r)[basis]-1e-12 or q['sr']>r['sr']+1e-12) for o,q in valid if o!=l) else 'F') for l,r in valid}
def mainrows(cell,n):
 return {l:r for l,r in OK.items() if r['cell']==cell and r['lib'] in [str(n),'-'] and r['run'] not in ['r05_growth','r05_demo_curve'] and 'k2' not in r['family'] and r['family']!='k5'}
def hist(cell):
 x={'p_l10':.844,'p_sp':.986,'g_l10':.870,'g_sp':.940}[cell]
 return {'label':'trace_dual_L5','sr':x,'v':1,'m':1,'ir':1.,'search_ir':1.,'dummy_ir':.952 if cell[0]=='p' else 1.,'family':'pure_inf','lib':'-','fit_bytes':None,'stage1_mode':'full','search_proxy':False,'search_q':None}
front={};all_main=set()
for cell in ['p_l10','p_sp','g_l10','g_sp']:
 for n in [50,500]:
  rs=mainrows(cell,n);all_main.update(rs);rs['trace_dual_L5']=hist(cell)
  marks={b:pareto(rs,b) for b in ['O','S','d']};front[f'{cell}_{n}']=marks
  put(f'### 9.{len(front)} {cell}, library {n}: all raw points')
  rows=[]
  for l,r in sorted(rs.items(),key=lambda lr:lr[1]['ir']):
   p=prices(r);tag=(' A' if r.get('stage1_mode')=='wrist_only' else '')+(' H' if l=='trace_dual_L5' else '')+(' U' if l=='sp_awm_h50_50' else '')
   search='—' if p['S'] is None else f"{p['S']:.5f}"+(' P' if r.get('search_proxy') and not r['family'].startswith('pure_inf') else '')
   fit='— (policy)' if r['family'].startswith('pure_inf') else ('—' if r.get('fit_bytes') is None else f"{r['fit_bytes']/1e6:.3f}")
   rows.append([f'`{l}`{tag}',f"{r['sr']:.3f}",f"{r['v']:.5f}",f"{r['m']:.5f}",f"{p['O']:.5f}"+(' †' if l=='sp_awm_h50_50' else ''),search,f"{p['d']:.5f}",'/'.join(marks[b].get(l,'U' if l=='sp_awm_h50_50' else '—') for b in ['O','S','d']),fit])
  table(['Arm alias','SR','v','m','Owner IR','+CPU search','dummy IR','O/S/d','Fit MB'],rows)
put('''† **Legacy R3 conflict:** `sp_awm_h50_50` has summary N=10,848, M=6,207, giving owner .63721; accepted raw-log deduplication gives N=10,851, M=5,874, with 764 duplicate decisions and 63 conflicting UIDs. The R4 printed cost is not used to conceal this mismatch. SR .986 is journal/summary-consistent; its cost is unverified and it cannot dominate a verified point. Other legacy summary count costs passed their raw audit. This anomaly does not affect the R5 ledger calculations.

K2 is excluded from the system by owner ruling (MISS step reduction is not an allowed system component). The next table preserves its observed SR and counts for inventory, and shows the mandated **full-MISS counterfactual accounting**, not its actual shortened-stage price; consult R4's K2 appendix for that different cost basis. K5 randomized interventions are diagnostic data, not ordinary deployable controller proposals.''')
diag={l:r for l,r in OK.items() if 'k2' in r['family'] or r['family']=='k5'}
table(['Excluded diagnostic alias','Reason','SR','v / m','Full-MISS counterfactual IR (K2) / owner IR (K5)','Fit MB'],[[f'`{l}`','K2 owner-excluded' if 'k2' in r['family'] else 'K5 randomized',sr(l),f"{r['v']:.5f} / {r['m']:.5f}",ir(l),'— (policy)' if r['family'].startswith('pure_inf') else mb(l)] for l,r in diag.items()])
put('### 9.9 Certified-repeat pooling and deployment interpretation')
pool_groups=[('stock3',['g500','g500_repa','g500_repb']),('K7_l10_500_all4',tails),('K7_sp500_2',['k7_sp_tail1ug','r5b_p_sp_500_hand']),('wrist_sp50_2',['wrist_sp_50','r5t_p_sp_g50_wrist_rep']),('CL2_g_l10_500_2',['cl2_g_l10_500','r5b_g_l10_500_hand']),('CL2_g_sp500_2',['cl2_g_sp_500','r5b_g_sp_500_hand']),('pi_policy_l10_L10_2',['inf_l10_L10','inf_l10_L10b']),('pi_policy_l10_L5_2',['inf_l10_s1001','inf_l10_s2001']),('pi_policy_sp_L5_2',['inf_sp_s1001','inf_sp_s2001'])]
def pooledrow(name,ls):
 r=dict(A[ls[0]]);N=sum(A[l]['N'] for l in ls);r['sr']=float(np.mean([A[l]['sr'] for l in ls]));r['ir']=poolcost(ls)
 for k in ['v','m','dummy_ir','search_ir','search_ms']:
  if all(A[l].get(k) is not None for l in ls):r[k]=sum(A[l]['N']*A[l][k] for l in ls)/N
 r['label']=name;r['N']=N;return r
pools={name:pooledrow(name,ls) for name,ls in pool_groups}
table(['Configuration pool','Runs','SR mean','Owner IR (pooled decisions)'],[[name,len(ls),f"{pools[name]['sr']:.5f}",f"{pools[name]['ir']:.5f}"] for name,ls in pool_groups])
configfront={}
for cell in ['p_l10','p_sp','g_l10','g_sp']:
 for n in [50,500]:
  rs=mainrows(cell,n)
  for name,ls in pool_groups:
   if all(l in rs for l in ls):
    for l in ls:del rs[l]
    rs[name]=pools[name]
  configfront[f'{cell}_{n}']={b:[l for l,m in pareto(rs,b).items() if m=='F'] for b in ['O','S','d']}
table(['Cell','Replicate-aware owner frontier (in ascending cost)','Owner+K8 frontier changes','dummy frontier changes'],[[cell,' → '.join(f'`{l}`' for l in sorted(v['O'],key=lambda l:(pools.get(l) or A[l])['ir'])),('same membership' if set(v['S'])==set(v['O']) else 'added '+(', '.join(sorted(set(v['S'])-set(v['O']))) or 'none')+'; removed '+(', '.join(sorted(set(v['O'])-set(v['S']))) or 'none')),('same membership' if set(v['d'])==set(v['O']) else 'added '+(', '.join(sorted(set(v['d'])-set(v['O']))) or 'none')+'; removed '+(', '.join(sorted(set(v['O'])-set(v['d']))) or 'none'))] for cell,v in configfront.items()])
put('''Replicate pooling removes the misleading raw claim that B1 hand K7 .906 beats pure policy .904 at lower cost. Four-run K7 is .88600 @ .20052, policy L=10 .902 @ .5. Replicate B changes the pooled estimate slightly but does not change the replicate-aware frontier membership in any cost panel. Under wrist prices, Q6 .892 @ .16209 point-dominates pooled K7, but their paired interval crosses zero and the price is assumed. Pooled estimates therefore change which configurations deserve attention without declaring a statistically proven winner. The K8 proxy makes Q6 slightly cheaper than C10 at l10-500 (.17702 versus .17836), so C10 leaves that search frontier; the tiny cost ordering depends on assumed wrist prices and inherited query timings. Dummy_cached makes full-camera C10 dominate Q6 at spatial-50, while restoring pure tail to the spatial-500 frontier. Historical trace_dual is shown in the raw tables, not pooled across protocols in this configuration panel. There is no unique “best” without an SR/cost/memory utility; the following choices are explicit deployment judgments, not fitted optima.''')
recommended=[
 ('p_l10_50','r5q1_c10_p_l10_50','C10 is the balanced cost/SR point; pure tail .706 costs .07640. Policy L=10 remains the higher-SR choice.'),
 ('p_l10_500','r5q6_p_l10_500_tail','Conditional Q6 candidate; wrist price and SR need confirmation. Conservative two-camera alternative is pooled K7 (.88600 @ .20052, 142.349 MB); C10 is cheaper with possible SR loss.'),
 ('p_sp_50','wrist_sp_50','Guard-only wrist pool .926 @ .15575 has a reproduced SR gain. Fit shown is the identical guard-only representation; full-camera C10 is .910 @ .14145.'),
 ('p_sp_500','tail1uc_sp_500','Pure-cache tail .982 is a simple no-policy option, .05350 with dummy. Conditional Q6 .990 @ .07419 uses 50.789 MB but has no proven SR advantage.'),
 ('g_l10_50',g('l10',50,'mix'),'G10 policy use helps the small bank; tail15 .570 @ .05004 is the low-cost option, policy L=10 .866 is the accuracy option.'),
 ('g_l10_500',g('l10',500,'one'),'Tail10 .830 @ .07450; tail15 .808 @ .05018 remains a valid cheaper choice because the SR gap is unresolved. G10 is dominated.'),
 ('g_sp_50',g('sp',50,'mix'),'G10 .920 @ .19794 buys SR over pure tails. Tail15 .864 @ .05127 is the low-cost choice; no significant reason to spend extra for tail10 .868.'),
 ('g_sp_500','gb_sp_500_ph2','R4 phase .976 @ .07834 is retained; tail15 .946 @ .05175 is the cheaper alternative. Scheduled policy does not help this cell.')]
table(['Cell','Balanced / simple deployable choice','Observed SR @ owner IR','Exact fit bytes','Interpretation / alternative'],[[cell,f'`{l}`',point(l),A[l]['fit_bytes'],note] for cell,l,note in recommended])
put('''These fit bytes exclude policy checkpoints, raw library archives, the native preload where still required, process duplication and device copies. Original native cache pickles are 1,103,155,631 / 430,792,483 bytes for π0.5 l10/spatial and 1,068,314,575 / 429,351,282 for GR00T (R4 footprint and Q5 hand-back). Compact-fit claims are useful, but removing the preload is a separate deployment change. Fifty-episode fits use only their deployment library; B1's external action normalization and any inherited outcome-trained diagnostics retain the qualifications in §7.''')
put('### 9.10 GR00T-native search sensitivity')
gcost=json.loads((ROOT/'exp/libero_groot/config/rit/cost_groot_libero_measured.json').read_text());gden=gcost['stage1_ms']+gcost['stage2_ms']+gcost['stage3_full_loop_ms']
rows=[]
for l,r in OK.items():
 if r['cell'].startswith('g') and r['run'] not in ['r05_growth','r05_demo_curve']:
  q=0 if r['family'].startswith('pure_inf') else r.get('search_ms')
  if q is not None:rows.append([f'`{l}`',f'{q:.4f}',ir(l),f'{r["ir"]+q/67.5:.5f}',f'{r["ir"]+q/gden:.5f}'])
table(['GR00T arm','K8 query ms / five controls','Owner IR','+search / 67.5 common proxy','+search / 41.441827 native reference'],rows)
put('''This denominator sensitivity leaves the key GR00T choices intact: ten-/fifteen-step tails remain much cheaper than mixed G10, G10 remains useful at 50 and point-dominated at 500. It does not turn K8 microbenchmarks into measurements of the loaded Q5 pipeline or a combined stage-1 graph.''')
put('### 9.11 Complete source index and exclusions')
put('''Each index entry expands to the per-arm summary/journal/DONE paths defined at the start. `fit_path`, exact bytes and SHA256 of summary/journal/marker are retained in `/tmp/r5_analysis/analysis.json`. q_v/q_b are the K8 ms values actually used; “—” means no measurement, with pure inference charged zero search. Every completed arm appears either in an eight-cell table, the diagnostic appendix, or §6. The source index supplies exact filenames instead of relying on changing root summaries.''')
table(['Alias','run / arm','Fit bytes','K8 q_v / q_b ms'],[[f'`{l}`',f"`{r['run']}/{r['arm']}`",r.get('fit_bytes') or '—',' / '.join('0' if x is None else f'{x:.3f}' for x in r['search_q']) if r.get('search_q') else '—'] for l,r in OK.items()])
put('''SKIPPED markers (excluded, not unfinished numerical slots):

- `r03_mx/r3mx_p_l10_ev_h50`, `r03_mx/r3mx_p_sp_ev_h50`.
- `r04_blind/r4b3_p_l10_50_ph2g`, `r04_blind/r4b3_p_l10_50_b0g`.
- `r04_cost/r4f_p_l10_inf_k2_L10`, `r04_cost/r4f_p_sp_inf_k2_L10`, `r04_cost/r4b2_p_l10_inf_k2_s1102`, `r04_cost/r4b2_p_sp_inf_k2_s1102`.

The R4 brief's deferred `r4_p_{l10,sp}_inf_s{1,2}` plans are represented by the later completed seeded pure-inference references, not additional measured arms. Smokes are excluded. Q3 produced no supported causal overlay and its rollout queue was canceled; K10 was canceled in the selection addendum; no Q6 phase variant or GR00T growth arm was run. These are absent experiments, not pending evidence. All requested R5 outcome slots are now filled, including replicate B.''')
(S/'frontiers.json').write_text(json.dumps({'raw':front,'pooled':configfront,'pools':pools},indent=1))
put('## 10. Synthesis, method, library, control, and cost: R4 → R5')
table(['Layer','What is held / changed','R5 evidence and implication'],[
 ['Synthesis','Kernel action combination; kref changes at fixed 500 bank','B1 π0.5 kref 8→5 yields −2.0 pp l10 and +1.0 pp spatial, both unresolved. Lower offline kernel error does not validate a better SR synthesis rule. Stored second-half execution belongs to control, not a new action synthesizer.'],
 ['Method / representation','Ridge, state weight, fitted PCA/whitening/confidence, wrist key','B1 ridge/state changes do not improve SR reliably. Q4 refit versus frozen200 changes SR +10.4/+16.2 pp at identical candidate contents; refitting matters, but this does not identify which individual fit component causes the gain. Q6 changes observation and guard geometry as well as price.'],
 ['Library','Contents / scale / acquisition provenance','Grow250 refit adds +14.4/+18.0 pp over same-manifest CL2-50; serving IR stays .152, acquisition is paid. The demo curve improves broadly, with a nonmonotone spatial point and endpoint source/kref confounds. Fifty- and 500-library conclusions are kept separate.'],
 ['Control including execution','Anchors, cached tails, policy commitment, rescue timing','Pure π0.5 tail gains +7.6/+6.0 pp l10 and +3.8/+2.8 pp spatial without policy calls. G10 buys SR at 50 but not 500. C10 realizes all nonterminal policy tails and lowers m, while unresolved SR losses prevent a preservation claim. D1 has insufficient reach/evidence.'],
 ['Cost implementation','Owner stage coefficients, camera work, retrieval path, storage','Dummy is a stipulated −.048v repricing; wrist is a ratio-transfer assumption. K8 adds CPU query cost outside inference. Q5 measures live latency but fails strict action parity. Fits shrink representation storage, while native preload/raw-bank/device memory remain separate.']])
put('''These axes interact. In particular, longer cached execution changes both the visited states and when guards request policy; refitting changes retrieval and hence guard reach; a wrist key changes observation quality and MISS rates as well as visual cost. The following arithmetic decompositions compare observed decision ratios, not causal mediation estimates and not a promise that the components can be added across independently run arms.''')
comp=[]
for s in ['l10','sp']:
 for n in [50,500]:
  b=pt(s,n);a=f'cl2_{s}_{n}';dv=.152*(A[b]['v']-A[a]['v']);dm=.848*(A[b]['m']-A[a]['m'])
  comp.append([f'π {s}-{n}: CL2 → pure tail',f"{100*(A[b]['sr']-A[a]['sr']):+.2f}",f'{dv:+.5f}',f'{dm:+.5f}',f"{A[b]['ir']-A[a]['ir']:+.5f}"])
for n in [50,500]:
 a=k7('l10',n);b=f'r5q1_c10_p_l10_{n}'
 comp.append([f'π l10-{n}: R4 K7 → C10',f"{100*(A[b]['sr']-A[a]['sr']):+.2f}",f"{.152*(A[b]['v']-A[a]['v']):+.5f}",f"{.848*(A[b]['m']-A[a]['m']):+.5f}",f"{A[b]['ir']-A[a]['ir']:+.5f}"])
for s in ['l10','sp']:
 for n in [50,500]:
  a=g(s,n,'one');b=g(s,n,'mix')
  comp.append([f'G {s}-{n}: tail10 → G10',f"{100*(A[b]['sr']-A[a]['sr']):+.2f}",f"{.148*(A[b]['v']-A[a]['v']):+.5f}",f"{.852*(A[b]['m']-A[a]['m']):+.5f}",f"{A[b]['ir']-A[a]['ir']:+.5f}"])
table(['Observed change','ΔSR pp','Vision term ΔIR','MISS term ΔIR','Total ΔIR'],comp)
put('''Pure-tail savings are entirely fewer visual decisions; C10 combines fewer vision anchors and fewer fresh policy calls per five controls. G10 versus a pure ten-step tail has almost the same vision cadence, so its extra cost is predominantly scheduled policy. Q6's full-camera counterfactual in §5 separates the observed control ratios from the assumed wrist stage price. Pure policy L=10 halves cost by executing ten controls/request and provides the execution baseline needed to avoid crediting every long-chunk gain to caching.

The R4 K5 result is inherited, not rederived: CALL−CACHE is +3.4 pp [0.4,6.6] at 500 and −0.2 pp [−4.0,3.2] at 50. Q3's [hand-back](q3_callvalue/HANDBACK.md) strengthens its limits: the scale contrast is +3.6 pp [−1.0,8.4], the 500 task-level interval includes zero, only 2/48 and 7/48 leaf contexts meet sample support, and no context has a positive conservative saving bound. All fitted suppression probabilities are zero under its declared 1 pp loss constraint. `arms_q3.json=[]` is a valid negative result. The apparent scale sign reversal is not a learned deployment rule, and these randomized stock-guard data cannot be transported automatically to K7, C10, GR00T or spatial. MISS inference is not an established general-purpose saving pool.''')
put('## 11. Settled results, rejected directions, and ranked proposals for the owner')
put('''**Settled within the measured protocol:** cached ten-step commitment improves π0.5 SR in all four cells while approximately halving pure-cache owner IR; the four-run K7 configuration retains a positive advantage over repeated stock on l10-500; wrist guard-only spatial-50 reproduces its favorable SR direction; paid growth and refitting improve held-out SR substantially; scheduled GR00T policy calls help 50-library tails but are unnecessary on the observed 500-library frontier. The 50 requirement materially changes the deployment answer: spatial-500 may drop policy, while spatial-50 and l10-50 still benefit from intervention. These are measured benchmark conclusions, not guarantees across tasks or hardware.

**Rejected for current adoption:** selecting B1 settings because offline RMS improves; promoting D1 from a single small-effect run; universal G10 scheduling at 500; automatic wrist+tail stacking at 50; treating kref endpoints as identical; equating a nonsignificant difference with preserved SR; claiming free library growth; suppressing policy calls using Q3's unsupported contexts; using K2 in the system; promoting GPU `serve` from top-1 agreement alone; or ranking deployment using the lucky .906 K7 repeat. R4's sparse-library phase continuation and relaxed no-progress ideas remain unrevived. “Rejected” here means unsupported by the current evidence, not mathematically impossible.

R5 is the last round in the current owner goal. The following are **ranked proposals for an owner decision**, not authorized or launched experiments:

1. **Close the reliability and price questions around the useful points.** The prescribed three-run and all-four-run K7 checks are complete and both pass the paired positive-effect criterion. If a new round is approved, repeat Q6/C10 against repeated K7 at both scales, predeclare an SR-loss margin and cost objective, and measure the wrist stage price on the actual graph. The final Q6-500 versus four-run K7 interval [−2.25,+3.50] pp and C10 interval [−4.35,+0.30] show why neither “same SR” claim is ready. Spatial-50 wrist guard-only deserves priority over unvalidated stack changes.
2. **Finish the retrieval implementation with strict parity and real memory accounting.** Reproduce Q5's task-8/init-45/step-46 top-16 boundary mismatch, resolve step-zero and later action/confidence differences, then ask the coordinator for a matched GPU-served evaluation and latency distribution. Integrate the supported controller only after this gate; measure native preload removal and actual resident bytes before claiming deployment memory reduction. Dummy_cached can be considered under its existing parity contract independently of unsupported wrist stacking.
3. **Test targeted GR00T intervention and commitment length where evidence supports value.** Focus on the 50 cells where G10 buys +11.0/+5.2 pp, retaining policy L=10 and both pure-tail lengths as controls. At 500, keep pure tail/phase as the baseline. A repeated, predeclared 10-versus-15 comparison is needed before paying roughly 50% more vision cost for the small numerical tail10 SR gains. Any adaptive rule needs bounded blindness, mandatory anchors and actual paid-call accounting.
4. **Validate library growth as a lifecycle decision.** Repeat the acquisition/evaluation split in reverse, hold controller and kref fixed, compare periodic refit with frozen append, and measure absolute cost-to-success as well as serving/lifecycle IR. Test the spatial-200 memory option with a declared noninferiority margin. Preserve the provenance distinction between demonstration data, paid policy rollouts, and outcome-trained fits; no GR00T growth extrapolation is justified yet.
5. **Reformulate offline selection around a prospective control objective.** Keep B1's negative SR-ranking result. A later study should distinguish synthesis error, dynamics/execution error and intervention value; enforce inductive/conditional split labels and library-only normalization where intended; preregister candidates and test ranks on new repeated loops. If causal call-value learning is reconsidered, collect randomized evidence under the exact intended controller and satisfy support requirements, rather than weakening Q3's constraints after seeing its null result.

**Completion:** all 52 R5 arms, both required K7 repeat pools, their dependent comparisons, and all eleven analysis sections are complete. The final frontier uses the four-run K7 estimate; the remaining proposals above require a separate owner decision.''')
# Report coverage check: every completed run represented in the correct cohort/table.
covered=all_main|set(diag)|{l for l,r in OK.items() if r['run'] in ['r05_growth','r05_demo_curve']}
assert covered==set(OK),(set(OK)-covered,covered-set(OK))
assert len(OK)==137 and len([r for r in OK.values() if r['run'].startswith('r05')])==52
text=''.join(parts)
for token,value in {'@SNAPSHOT@':datetime.fromisoformat(X['snapshot_utc']).astimezone(ZoneInfo('America/Chicago')).strftime('%Y-%m-%d %H:%M %Z'), '@NARMS@':len(OK), '@NAUDIT@':len(D), '@NDECISIONS@':f"{sum(d['N'] for d in D.values()):,}", '@NR5@':sum(r['run'].startswith('r05') for r in OK.values()), '@NPAIRS@':f"{len(X['pairs']):,}"}.items():text=text.replace(token,str(value))
assert 'TODO' not in text and '@SNAPSHOT@' not in text and not X['pending']
assert all(f'## {i}.' in text for i in range(1,12))
OUT.write_text(text)
print('Wrote',OUT,'bytes',OUT.stat().st_size,'completed arms',len(OK),'pending',X['pending'])
