suite: libero_spatial
apool_dir: /home/weiland/openpi/exp/common/data/db_init/libero/libero_spatial_apool
total_inits: 500
per_task_digests:
  pick_up_the_black_bowl_between_the_plate_and_the_ramekin_and_place_it_on_the_plate: cbbc73792ce546c9bec181fd328a411d3183074840b282671dee481511381d0a
  pick_up_the_black_bowl_from_table_center_and_place_it_on_the_plate: 27d5b81d739f969e40c72b6c88699e57a91ea61209946b21c593aae5990689cb
  pick_up_the_black_bowl_in_the_top_drawer_of_the_wooden_cabinet_and_place_it_on_the_plate: deef3df529e0bb57658b973bbb3baf02b02922db065c025a73ebfcd11eb54d46
  pick_up_the_black_bowl_next_to_the_cookie_box_and_place_it_on_the_plate: ab86fb7b5942dc0fec762eae57e72bf636106b1c10ad8ce57227723d8eb9a81b
  pick_up_the_black_bowl_next_to_the_plate_and_place_it_on_the_plate: f43df2d80042130ac8770590d83f1a1e6fd4df7479aebc392aa2ed6e3bd0b83e
  pick_up_the_black_bowl_next_to_the_ramekin_and_place_it_on_the_plate: 9b6927b6ef03460ab055141e1a1154ad85e5e290058d8ed3a8a314aff911f864
  pick_up_the_black_bowl_on_the_cookie_box_and_place_it_on_the_plate: 0627f5f5ce3ef23be546571012be8ef603d93bcb4032bc80feb34937ba580140
  pick_up_the_black_bowl_on_the_ramekin_and_place_it_on_the_plate: 2d2c50b7dcbf861fffa94d576f217ed34153e57487010d7a109a220d4d97189b
  pick_up_the_black_bowl_on_the_stove_and_place_it_on_the_plate: ea9cba2814bc166f3682f3f5a97329467839bcf584069cd419191b6c17adae25
  pick_up_the_black_bowl_on_the_wooden_cabinet_and_place_it_on_the_plate: 08b0ac928dcc524a66d963851a6a4eece9aeb782b38466006e403a70e3287867
rollup_sha256: 0eeece46a08b958efe7b7db4e6b13d3269b0433be4e20fbae3c0f352bc3aca9c
disjoint_from_difference_pool:
  pick_up_the_black_bowl_between_the_plate_and_the_ramekin_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_from_table_center_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_in_the_top_drawer_of_the_wooden_cabinet_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_next_to_the_cookie_box_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_next_to_the_plate_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_next_to_the_ramekin_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_on_the_cookie_box_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_on_the_ramekin_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_on_the_stove_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
  pick_up_the_black_bowl_on_the_wooden_cabinet_and_place_it_on_the_plate:
    a_count: 50
    b_count: 50
    shared: 0
