"""Statistical read-out of the weighted-sum search from the per-cell journals.

Every cell evaluates the SAME task x init-state grid: the episode's seed is
``base_seed + orig_init_state_idx`` (``episode_runner.py``) and the scene is
pinned to ``layout_and_style_ids=[(1, 1)]``, so a given ``(task, idx)`` key is
the *same initial state* in every cell.  Cell-vs-cell comparison is therefore
paired, and the paired test is far sharper than treating cells as independent
samples -- most of the outcome variance is carried by the initial state rather
than by the retrieval weights.

Reads the raw ``journal_ws1-*.jsonl`` files (not the per-cell summaries) so the
per-episode outcomes stay available for pairing.  Journals from both hosts must
be merged into one directory first; see the plan's drain runbook.

Outputs
  * per-cell ``macro_sr`` ranking (task-equal-weight mean, matching the
    summarizer) with the per-task success table,
  * an initial-state dominance diagnostic (how much of the outcome is decided
    before the retrieval config gets a vote),
  * a paired sign-flip randomization test of leader-vs-every-other-cell, which
    yields the set of cells statistically tied with the leader -- the honest
    answer to "which config won" when a single cell is only 104 episodes.

Usage::

    python exp/robocasa365/analyze_ws_search_stats.py --journal-dir <dir>
    python exp/robocasa365/analyze_ws_search_stats.py --journal-dir <dir> --csv out.csv
"""

from __future__ import annotations

import argparse
import collections
import csv
import json
import pathlib
import random
import statistics

EPISODES_PER_TASK = 8
RESAMPLES = 20000


def load_journals(
    journal_dir: pathlib.Path, episodes: int, run_prefix: str = "ws1"
) -> tuple[dict[str, dict[tuple[str, int], bool]], list[tuple[str, int]]]:
    """cid -> {(task, init_state_idx): success} plus the canonical episode grid.

    A cell is kept only when it covers the whole grid.  Checking each cell
    against its *own* task count is not enough: a cell caught mid-flight can
    hold a whole number of finished tasks and still be missing others.
    """
    raw: dict[str, dict[tuple[str, int], bool]] = {}
    for path in sorted(journal_dir.glob(f"journal_{run_prefix}-*.jsonl")):
        outcomes: dict[tuple[str, int], bool] = {}
        for line in path.read_text().splitlines():
            if not line.strip():
                continue
            rec = json.loads(line)
            if not rec.get("accepted") or rec.get("status") not in ("done", "failed"):
                continue
            _, _, tail = rec["task_uid"].rpartition("__")
            task, _, rest = tail.partition(":")
            outcomes[(task, int(rest.split(":")[-1]))] = bool(rec["success"])
        raw[path.name[len(f"journal_{run_prefix}-"):].split("__l1s1")[0]] = outcomes

    seen = collections.Counter(t for o in raw.values() for t, _ in o)
    quorum = max(seen.values()) / 2 if seen else 0
    grid = [(t, i) for t in sorted(t for t, n in seen.items() if n >= quorum) for i in range(episodes)]

    cells, partial = {}, {}
    for cid, outcomes in raw.items():
        if all(k in outcomes for k in grid):
            cells[cid] = outcomes
        else:
            partial[cid] = sum(1 for k in grid if k in outcomes)
    if partial:
        print(f"skipped {len(partial)} in-flight/partial cells: "
              + ", ".join(f"{c}({n}/{len(grid)})" for c, n in sorted(partial.items())[:4])
              + (" ..." if len(partial) > 4 else ""))
    return cells, grid


def macro_sr(outcomes, tasks, idxs) -> float:
    return sum(sum(outcomes[(t, i)] for i in idxs) / len(idxs) for t in tasks) / len(tasks)


def signflip_p(diffs: list[int], weight: float, rng: random.Random, resamples: int) -> tuple[float, float]:
    """Two-sided paired randomization test on per-episode outcome differences.

    Under the null that the two cells are exchangeable for a given initial
    state, each nonzero difference flips sign with probability 1/2 -- so the
    reference distribution is generated by sign flips rather than by resampling
    episodes (which would be far too coarse at 8 draws per task).
    """
    nz = [d for d in diffs if d]
    observed = sum(diffs) * weight
    if not nz:
        return observed, 1.0
    target = abs(sum(nz))
    hits = 0
    for _ in range(resamples):
        total = 0
        for _d in nz:
            total += 1 if rng.getrandbits(1) else -1
        if abs(total) >= target:
            hits += 1
    return observed, (hits + 1) / (resamples + 1)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--journal-dir", required=True, help="directory holding the merged journal_ws1-*.jsonl")
    ap.add_argument("--index", default="", help="default: exp/robocasa365/config/ws_search/<teacher>/index.json")
    ap.add_argument("--teacher", default="groot_tp", choices=("groot_tp", "pi05"))
    ap.add_argument("--run-prefix", default="ws1", help="round tag the journals were written under")
    ap.add_argument("--exclude-tasks", default="",
                    help="comma-separated tasks dropped from every readout (owner-ruled dead "
                         "tasks: ~zero SR under every cell add noise-floor dilution, no signal); "
                         "filtering is retroactive — every cell measured every task")
    ap.add_argument("--episodes", type=int, default=EPISODES_PER_TASK)
    ap.add_argument("--resamples", type=int, default=RESAMPLES)
    ap.add_argument("--alpha", type=float, default=0.05)
    ap.add_argument("--csv", default="", help="write the ranking table here")
    ap.add_argument("--seed", type=int, default=12345)
    args = ap.parse_args()

    root = pathlib.Path(__file__).resolve().parent
    index_path = pathlib.Path(args.index) if args.index else (
        root / "config" / "ws_search" / args.teacher / "index.json")
    index = json.loads(index_path.read_text()) if index_path.exists() else {}

    cells, keys = load_journals(pathlib.Path(args.journal_dir), args.episodes, args.run_prefix)
    if not cells:
        print("no complete cells found")
        return
    dropped = {t.strip() for t in args.exclude_tasks.split(",") if t.strip()}
    if dropped:
        keys = [(t, i) for t, i in keys if t not in dropped]
        print(f"excluded tasks ({len(dropped)}): {', '.join(sorted(dropped))} "
              f"-- macro_sr below is over the remaining task set")
    tasks = sorted({t for t, _ in keys})
    idxs = sorted({i for _, i in keys})
    print(f"complete cells: {len(cells)}/{len(index) or '?'}   tasks: {len(tasks)}   "
          f"init states/task: {len(idxs)}   episodes/cell: {len(keys)}")

    ranked = sorted(cells, key=lambda c: -macro_sr(cells[c], tasks, idxs))
    leader = ranked[0]

    # --- how much does the initial state decide on its own? ---
    per_key = [sum(cells[c][k] for c in cells) / len(cells) for k in keys]
    grand = sum(per_key) / len(per_key)
    unanimous = sum(1 for v in per_key if v in (0.0, 1.0)) / len(per_key)
    var_ratio = statistics.pvariance(per_key) / (grand * (1 - grand) / len(cells))
    print(f"\ninitial-state dominance: grand SR={grand:.3f}; "
          f"{unanimous:.0%} of initial states get the same verdict from every cell; "
          f"between-state variance is {var_ratio:.0f}x the independence null")

    # --- paired leader-vs-rest ---
    rng = random.Random(args.seed)
    weight = 1.0 / (len(tasks) * len(idxs))
    rows, tied = [], [leader]
    for cid in ranked:
        m = macro_sr(cells[cid], tasks, idxs)
        if cid == leader:
            rows.append((cid, m, 0.0, 1.0, True))
            continue
        diffs = [int(cells[leader][k]) - int(cells[cid][k]) for k in keys]
        d, p = signflip_p(diffs, weight, rng, args.resamples)
        is_tied = p >= args.alpha
        tied.append(cid) if is_tied else None
        rows.append((cid, m, d, p, is_tied))

    print(f"\nleader: {leader}  macro_sr={rows[0][1]:.3f}")
    print(f"cells statistically tied with the leader (paired sign-flip, alpha={args.alpha}): "
          f"{len(tied)}/{len(cells)}")
    print("\nrank  macro_sr   d(lead-cell)   p_paired  cid")
    for r, (cid, m, d, p, is_tied) in enumerate(rows[:15], 1):
        mark = "  TIED" if is_tied else ""
        print(f"{r:>4}  {m:.3f}     {d:+.3f}        {p:.4f}{mark}  {cid}")

    # --- what the weights actually buy: marginal means over the design ---
    # Reading the top of a 132-cell leaderboard overstates whatever the noise
    # favoured; the marginal mean at each weight level pools many cells and is
    # the honest readout of a factorial sweep.
    fields = ("vision_0", "vision_1", "vision_2", "robot_state")
    if index:
        print("\nweight marginals (mean macro_sr over cells at each level; n in brackets):")
        for f in fields:
            levels: dict[float, list[float]] = {}
            for cid in cells:
                w = index.get(cid, {}).get("weights", {})
                if not w:
                    continue
                levels.setdefault(round(float(w.get(f, 0.0)), 3), []).append(
                    macro_sr(cells[cid], tasks, idxs))
            if len(levels) < 2:
                continue
            cells_txt = "  ".join(
                f"{lv:.3f}:{sum(v) / len(v):.3f}[{len(v)}]" for lv, v in sorted(levels.items()))
            print(f"  {f:<13} {cells_txt}")

    print("\nper-task success across cells (min / mean / max):")
    for t in tasks:
        xs = [sum(cells[c][(t, i)] for i in idxs) / len(idxs) for c in cells]
        print(f"  {t:<26} {min(xs):.2f} / {sum(xs) / len(xs):.2f} / {max(xs):.2f}")

    if args.csv:
        fields = ("vision_0", "vision_1", "vision_2", "robot_state")
        out = pathlib.Path(args.csv)
        with out.open("w", newline="") as fh:
            w = csv.writer(fh)
            w.writerow(["rank", "cid", "macro_sr", "d_vs_leader", "p_paired", "tied_with_leader",
                        *(f"w_{f}" for f in fields), *(f"sr_{t}" for t in tasks)])
            for r, (cid, m, d, p, is_tied) in enumerate(rows, 1):
                weights = index.get(cid, {}).get("weights", {})
                w.writerow([r, cid, f"{m:.4f}", f"{d:+.4f}", f"{p:.4f}", int(is_tied),
                            *(weights.get(f, 0.0) for f in fields),
                            *(f"{sum(cells[cid][(t, i)] for i in idxs) / len(idxs):.3f}" for t in tasks)])
        print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
