arms:
- arm: l10_gst_f00w00v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w00v20.yaml
  suite: libero_10
- arm: l10_gst_f00w00v40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w00v40.yaml
  suite: libero_10
- arm: l10_gst_f00w00v60
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w00v60.yaml
  suite: libero_10
- arm: l10_gst_f00w00v80
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w00v80.yaml
  suite: libero_10
- arm: l10_gst_f00w20v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w20v00.yaml
  suite: libero_10
- arm: l10_gst_f00w20v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w20v20.yaml
  suite: libero_10
- arm: l10_gst_f00w20v40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w20v40.yaml
  suite: libero_10
- arm: l10_gst_f00w20v60
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w20v60.yaml
  suite: libero_10
- arm: l10_gst_f00w40v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w40v00.yaml
  suite: libero_10
- arm: l10_gst_f00w40v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w40v20.yaml
  suite: libero_10
- arm: l10_gst_f00w40v40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w40v40.yaml
  suite: libero_10
- arm: l10_gst_f00w60v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w60v00.yaml
  suite: libero_10
- arm: l10_gst_f00w60v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w60v20.yaml
  suite: libero_10
- arm: l10_gst_f00w80v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f00w80v00.yaml
  suite: libero_10
- arm: l10_gst_f20w00v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w00v00.yaml
  suite: libero_10
- arm: l10_gst_f20w00v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w00v20.yaml
  suite: libero_10
- arm: l10_gst_f20w00v40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w00v40.yaml
  suite: libero_10
- arm: l10_gst_f20w00v60
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w00v60.yaml
  suite: libero_10
- arm: l10_gst_f20w20v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w20v00.yaml
  suite: libero_10
- arm: l10_gst_f20w20v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w20v20.yaml
  suite: libero_10
- arm: l10_gst_f20w20v40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w20v40.yaml
  suite: libero_10
- arm: l10_gst_f20w40v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w40v00.yaml
  suite: libero_10
- arm: l10_gst_f20w40v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w40v20.yaml
  suite: libero_10
- arm: l10_gst_f20w60v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f20w60v00.yaml
  suite: libero_10
- arm: l10_gst_f40w00v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f40w00v00.yaml
  suite: libero_10
- arm: l10_gst_f40w00v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f40w00v20.yaml
  suite: libero_10
- arm: l10_gst_f40w00v40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f40w00v40.yaml
  suite: libero_10
- arm: l10_gst_f40w20v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f40w20v00.yaml
  suite: libero_10
- arm: l10_gst_f40w20v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f40w20v20.yaml
  suite: libero_10
- arm: l10_gst_f40w40v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f40w40v00.yaml
  suite: libero_10
- arm: l10_gst_f60w00v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f60w00v00.yaml
  suite: libero_10
- arm: l10_gst_f60w00v20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f60w00v20.yaml
  suite: libero_10
- arm: l10_gst_f60w20v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f60w20v00.yaml
  suite: libero_10
- arm: l10_gst_f80w00v00
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_gst_f80w00v00.yaml
  suite: libero_10
- arm: l10_rit_k1_ir20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir20.yaml
  suite: libero_10
- arm: l10_rit_k1_ir25
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir25.yaml
  suite: libero_10
- arm: l10_rit_k1_ir30
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir30.yaml
  suite: libero_10
- arm: l10_rit_k1_ir35
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir35.yaml
  suite: libero_10
- arm: l10_rit_k1_ir40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir40.yaml
  suite: libero_10
- arm: l10_rit_k1_ir45
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir45.yaml
  suite: libero_10
- arm: l10_rit_k1_ir50
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir50.yaml
  suite: libero_10
- arm: l10_rit_k1_ir55
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir55.yaml
  suite: libero_10
- arm: l10_rit_k1_ir60
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir60.yaml
  suite: libero_10
- arm: l10_rit_k1_ir65
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir65.yaml
  suite: libero_10
- arm: l10_rit_k1_ir70
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir70.yaml
  suite: libero_10
- arm: l10_rit_k1_ir75
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir75.yaml
  suite: libero_10
- arm: l10_rit_k1_ir80
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir80.yaml
  suite: libero_10
- arm: l10_rit_k1_ir85
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir85.yaml
  suite: libero_10
- arm: l10_rit_k1_ir90
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir90.yaml
  suite: libero_10
- arm: l10_rit_k1_ir95
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k1_ir95.yaml
  suite: libero_10
- arm: l10_rit_k2_ir20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir20.yaml
  suite: libero_10
- arm: l10_rit_k2_ir25
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir25.yaml
  suite: libero_10
- arm: l10_rit_k2_ir30
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir30.yaml
  suite: libero_10
- arm: l10_rit_k2_ir35
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir35.yaml
  suite: libero_10
- arm: l10_rit_k2_ir40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir40.yaml
  suite: libero_10
- arm: l10_rit_k2_ir45
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir45.yaml
  suite: libero_10
- arm: l10_rit_k2_ir50
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir50.yaml
  suite: libero_10
- arm: l10_rit_k2_ir55
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir55.yaml
  suite: libero_10
- arm: l10_rit_k2_ir60
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir60.yaml
  suite: libero_10
- arm: l10_rit_k2_ir65
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir65.yaml
  suite: libero_10
- arm: l10_rit_k2_ir70
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir70.yaml
  suite: libero_10
- arm: l10_rit_k2_ir75
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir75.yaml
  suite: libero_10
- arm: l10_rit_k2_ir80
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir80.yaml
  suite: libero_10
- arm: l10_rit_k2_ir85
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir85.yaml
  suite: libero_10
- arm: l10_rit_k2_ir90
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir90.yaml
  suite: libero_10
- arm: l10_rit_k2_ir95
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k2_ir95.yaml
  suite: libero_10
- arm: l10_rit_k3_ir20
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir20.yaml
  suite: libero_10
- arm: l10_rit_k3_ir25
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir25.yaml
  suite: libero_10
- arm: l10_rit_k3_ir30
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir30.yaml
  suite: libero_10
- arm: l10_rit_k3_ir35
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir35.yaml
  suite: libero_10
- arm: l10_rit_k3_ir40
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir40.yaml
  suite: libero_10
- arm: l10_rit_k3_ir45
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir45.yaml
  suite: libero_10
- arm: l10_rit_k3_ir50
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir50.yaml
  suite: libero_10
- arm: l10_rit_k3_ir55
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir55.yaml
  suite: libero_10
- arm: l10_rit_k3_ir60
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir60.yaml
  suite: libero_10
- arm: l10_rit_k3_ir65
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir65.yaml
  suite: libero_10
- arm: l10_rit_k3_ir70
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir70.yaml
  suite: libero_10
- arm: l10_rit_k3_ir75
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir75.yaml
  suite: libero_10
- arm: l10_rit_k3_ir80
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir80.yaml
  suite: libero_10
- arm: l10_rit_k3_ir85
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir85.yaml
  suite: libero_10
- arm: l10_rit_k3_ir90
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir90.yaml
  suite: libero_10
- arm: l10_rit_k3_ir95
  yaml: /home/weiland/projects/openpi/exp/libero_groot/config/rit/libero_10/arms/l10_rit_k3_ir95.yaml
  suite: libero_10
