enabled: true
timer:
  enabled: false
keys:
  vision_0:
    enabled: true
    weight: 0.5
  vision_1:
    enabled: true
    weight: 0.4166666666666667
  vision_2:
    enabled: false
    weight: 0.0
  prompt_emb:
    enabled: false
    weight: 0.0
  robot_state:
    enabled: true
    weight: 0.08333333333333333
key_builder:
  type: cp1_groot_libero_spatial_pool_16
checkpoints:
  cp1:
    enabled: true
    gate:
      type: always_search
    judge:
      type: always_hit
    search_strategy:
      type: weighted_score_sum_knn
      top_k: 1
      step_filter: all
      field_similarity:
        vision_0:
          type: cosine
        vision_1:
          type: cosine
        robot_state:
          type: l2
          to_similarity:
            type: exp
            tau: 1.0
      score_normalization:
        type: per_field
        fields:
          vision_0:
            method: zscore
            params:
              mu: 0.8359259302165681
              sigma: 0.041713437794830596
              squash: tanh
          vision_1:
            method: zscore
            params:
              mu: 0.8185005413036874
              sigma: 0.03624461405779446
              squash: tanh
          robot_state:
            method: zscore
            params:
              mu: -1.674452230500367
              sigma: 0.6613830106027817
              squash: tanh
  cp3:
    enabled: false
    search_strategy:
      type: weighted_rrf_knn
backend:
  type: in_memory
  vector_dims:
    vision_0: 32768
    vision_1: 32768
    prompt_emb: 2048
    robot_state: 8
  in_memory:
    preload_path: /data/libero_cache/libraries/libero_10/libero_10_sp16_S3.pkl
    index_type: brute_force
write_policy:
  type: never
