#!/usr/bin/env bash
# Drive the ActionCache-baseline cohort into the collectors (plan §3.9): N
# client tmux sessions, the i-th runs its tasks strictly one after another
# against port BASE+i, so each collector ever sees one connection.
#
# Default task dealing: client i runs task i, then task i+N (N=5 -> 10 tasks).
# The episode filter per task comes from verify_shadow_h5.py --emit-full-filter
# (first attempt) or from the retry filter split per task (re-runs); the pool
# is the RIT cohort's shadow_pool so the client's trial index is the position
# in the sampled file and the filter carries the orig index.
#
# Every client writes --save-episode-results with the termination evidence the
# verifier requires; each per-client driver script and its exit ledger are
# kept in the attempt directory as evidence.
#
# usage: run_acb_collect_clients.sh <suite> <repo> <python> <attempt> <filter-dir> [root] [base-port] [n] [trials]
set -eu

SUITE=${1:?suite}
REPO=${2:?repo}
PY=${3:?python}
ATTEMPT=${4:?attempt index}
FILTERS=${5:?directory with filter_task_<t>.json}
ROOT=${6:-/data/libero_cache/acb_shadow_h5}
BASE=${7:-8030}
N=${8:-5}
TRIALS=${9:-15}

ADIR=$ROOT/$SUITE/attempt_$ATTEMPT
POOL=$REPO/exp/libero_groot/data/rit/shadow/$SUITE/shadow_pool
[ -d "$ADIR" ] || { echo "missing attempt dir $ADIR (start the collectors first)"; exit 1; }
[ -d "$POOL" ] || { echo "missing cohort pool $POOL"; exit 1; }

NGPU=$(nvidia-smi --query-gpu=index --format=csv,noheader | wc -l)
for i in $(seq 0 $((N-1))); do tmux kill-session -t "acbcli$i" 2>/dev/null || true; done
sleep 3

launched=0
for i in $(seq 0 $((N-1))); do
  P=$((BASE+i))
  G=$((i % NGPU))
  DRV=$ADIR/client_$i.sh
  {
    echo "#!/usr/bin/env bash"
    echo "# generated by run_acb_collect_clients.sh $(date -Is): client $i -> port $P, GPU $G"
    echo "cd $REPO"
    echo "export HOME=$HOME LIBERO_CONFIG_PATH=$HOME/.libero MUJOCO_EGL_DEVICE_ID=$G PYTHONPATH=$REPO:$REPO/src"
  } > "$DRV"
  ntask=0
  for t in $(seq "$i" "$N" 9); do
    F=$FILTERS/filter_task_$t.json
    if [ ! -f "$F" ] || [ "$(tr -d ' \n' < "$F")" = "[]" ]; then
      echo "client $i: task $t has no filter rows, skipped"; continue
    fi
    cp "$F" "$ADIR/filter_task_$t.json"
    cat >> "$DRV" <<EOS
$PY examples/libero/main.py \\
  --host 127.0.0.1 --port $P --task-suite-name $SUITE --task-ids $t \\
  --num-trials-per-task $TRIALS --num-workers 1 --num-steps-wait 10 --seed 7 \\
  --resize-size 256 --replan-steps 5 --init-states-dir $POOL \\
  --episode-filter $ADIR/filter_task_$t.json --save-episode-results \\
  --episode-results-path $ADIR/client_task_$t.json 2>&1 | tee $ADIR/client_task_$t.log
rc=\${PIPESTATUS[0]}
echo "ACBCLI_EXIT=\$rc" | tee -a $ADIR/client_task_$t.log
echo "{\"task_id\": $t, \"port\": $P, \"client\": $i, \"exit\": \$rc, \"ended_at\": \"\$(date -Is)\"}" >> $ADIR/client_exit_$i.jsonl
sleep 5
EOS
    ntask=$((ntask+1))
  done
  if [ "$ntask" -eq 0 ]; then rm -f "$DRV"; echo "client $i: nothing to run"; continue; fi
  echo "echo ACBCLI_DONE=$i" >> "$DRV"
  chmod +x "$DRV"
  tmux new -s "acbcli$i" -d "bash $DRV 2>&1 | tee $ADIR/client_$i.log"
  launched=$((launched+1))
  sleep 2
done

sleep 10
echo "== launched $launched client chain(s) =="
tmux ls 2>/dev/null | grep -c '^acbcli' | sed 's/^/client sessions: /'
