enabled: true
timer:
  enabled: false
keys:
  vision_0:
    enabled: true
    weight: 0.0
  vision_1:
    enabled: true
    weight: 0.875
  vision_2:
    enabled: true
    weight: 0.125
  prompt_emb:
    enabled: false
    weight: 0.0
  robot_state:
    enabled: true
    weight: 0.0
key_builder:
  type: cp1_spatial_pool_16
checkpoints:
  cp1:
    enabled: true
    gate:
      type: always_search
    judge:
      type: always_hit
    search_strategy:
      type: weighted_score_sum_knn
      top_k: 1
      step_filter: all
      field_similarity:
        vision_1:
          type: cosine
        vision_2:
          type: cosine
      score_normalization:
        type: per_field
        fields:
          vision_1:
            method: zscore
            params:
              mu: 0.9666321025848761
              sigma: 0.008126642579973977
              squash: tanh
          vision_2:
            method: zscore
            params:
              mu: 0.9748870158727465
              sigma: 0.009871054158253534
              squash: tanh
  cp3:
    enabled: false
    search_strategy:
      type: weighted_rrf_knn
backend:
  type: in_memory
  vector_dims:
    vision_0: 32768
    vision_1: 32768
    vision_2: 32768
    prompt_emb: 2048
    robot_state: 32
  in_memory:
    preload_path: /data/robocasa365_cache/cache_artifacts_l1s1/pi05_spatial_pool_16_n5.pkl
    index_type: brute_force
write_policy:
  type: never
