"""Render audited outputs; never changes the frozen analysis or source data."""
from pathlib import Path
import hashlib
import json
import math

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import norm

HERE = Path(__file__).resolve().parent
CELLS = [f'{m}_{s}_{n}' for m in ('pi05', 'groot') for s in ('l10', 'sp') for n in (50, 500)]
LABEL = {c: c.replace('pi05', 'π0.5').replace('groot', 'GR00T').replace('_', ' ') for c in CELLS}


def md(headers, rows):
    return '\n'.join(['| ' + ' | '.join(headers) + ' |', '| ' + ' | '.join(['---'] * len(headers)) + ' |'] +
                     ['| ' + ' | '.join(map(str, row)) + ' |' for row in rows]) + '\n'


def interval(r, lo='lo_95', hi='hi_95', est='estimate', scale=100):
    if pd.isna(r[est]):
        return 'unavailable'
    point = f'{scale*r[est]:+.2f}'
    return point + (f' [{scale*r[lo]:+.2f}, {scale*r[hi]:+.2f}]' if pd.notna(r[lo]) else ' [unavailable]')


def main():
    fx = pd.read_csv(HERE/'pilot_all/effects.csv')
    primary = pd.read_csv(HERE/'final_pilot/primary64.csv')
    plans = pd.read_csv(HERE/'final_pilot/measured_continuation_precision.csv')
    ab = pd.read_csv(HERE/'final_exploratory/AB_three_replicates.csv').set_index('cell')
    abl = pd.read_csv(HERE/'final_exploratory/ablations.csv')
    frontier = pd.read_csv(HERE/'final_exploratory/frontier.csv')
    text = ['# Q3 complete numerical supplement', '',
            'Generated by `build_final_tables.py` from the audited CSVs. SR effects/intervals are percentage points. '
            'Missing intervals are unavailable, not zero. Only section 1 is the frozen primary family; '
            'section 2 contains prespecified secondary diagnostics, section 3 measured-variance planning, '
            'and section 4 post-hoc evidence.', '']
    text += ['## 1. Frozen 64 primary SR contrasts', '']
    order = ['factorial_call','factorial_at_guard','factorial_pre_guard','coverage_enrichment','guard_enrichment',
             'duration10_vs5','hold3_vs1','window_delay0_vs2']
    for c in CELLS:
        d = primary[primary.cell.eq(c)].set_index('contrast')
        text += ['### '+LABEL[c], '', md(['Contrast', 'Effect [pointwise 95%]', 'Effect [simultaneous 64]', 'df'],
            [[s, interval(d.loc[s]), interval(d.loc[s], 'lo_primary','hi_primary'), d.loc[s,'df']] for s in order])]
    text += ['## 2. Prespecified secondary diagnostics (not selection evidence)', '',
             'All-pilot, unadjusted pointwise 95% intervals below; nomination uses calibration only.', '']
    for gate in ('coverage_high','neighbour_high','early','nonadvance','never_called','G_alpha20','shadow_high','k4_high'):
        rows=[]
        for c in CELLS:
            row=[LABEL[c]]
            for cohort in ('factorial','dose125','dose25','dose50'):
                name='coverage_enrichment' if cohort=='factorial' and gate=='coverage_high' else f'{cohort}:{gate}:enrichment'
                d=fx[fx.cell.eq(c)&fx.split.eq('all')&fx.outcome.eq('Y')&fx.contrast.eq(name)]
                row.append(interval(d.iloc[0]) if len(d) else 'missing')
            rows.append(row)
        text += ['### '+gate, '', md(['Cell','Factorial','Fixed dose 1/8','Fixed dose 1/4','Fixed dose 1/2'],rows)]
    gain=pd.read_csv(HERE/'pilot_all/gain_per_call.csv')
    text += ['### SR per incremental future MISS', '',
             'Secondary ratio for the whole factorial package, including future changes in calls. '
             'This is not the causal effect of an isolated inference computation.', '',
             md(['Cell','SR points per extra MISS [95%]','Status'],
                [[LABEL[c], interval(r,'lo95','hi95'),r.status] for c in CELLS
                 for _,r in gain[gain.cell.eq(c)&gain.split.eq('all')&gain.contrast.eq('factorial_call')].iterrows()])]
    text += ['## 3. Measured-variance continuation forecasts', '',
             'Conditional forecasts, not results from the continuation. Negative estimated between-init covariance '
             'is preserved in raw ICC and clipped to zero only in the conservative projection. Full=500/cohort/cell; '
             'full validation=400; continuation-only validation=370.', '']
    for contrast in ('B-A','B-P10','factorial_call','coverage_enrichment','window_delay0_vs2'):
        rows=[]
        for c in CELLS:
            d=plans[plans.cell.eq(c)&plans.contrast.eq(contrast)]
            f=d[d.stage.eq('full')&d.split.eq('all')].iloc[0]
            cv=d[d.stage.eq('continuation')&d.split.eq('validation')].iloc[0]
            rows.append([LABEL[c],f'{f.within_task_variance:.4f}',f'{f.icc_raw:.3f}',f'{f.icc_planning:.3f}',
                         f'{f.n_eff_conservative:.1f}',f'{100*f.halfwidth_95:.2f}',f'{100*f.halfwidth_sim64:.2f}',
                         f'{100*cv.halfwidth_95:.2f}',f'{100*cv.halfwidth_sim64:.2f}',f'{100*f.mde80:.2f}'])
        text += ['### '+contrast,'',md(['Cell','Within-task variance','Raw ICC','Planning ICC','Full n_eff',
            'Full ±95% (pp)','Full ±sim64 (pp)','New validation ±95%','New validation ±sim64','Full MDE80 (pp)'],rows)]
    ni=plans[plans.contrast.eq('B-P10')&plans.stage.eq('full')&plans.split.eq('all')].copy()
    ni['variance_for_planning']=ni.sigma_init_raw.clip(lower=0)+ni.sigma_within
    ni['effective_pairs_1pp_NI80']=np.ceil((norm.ppf(.95)+norm.ppf(.8))**2*ni.variance_for_planning/.01**2).astype(int)
    ni[['cell','variance_for_planning','effective_pairs_1pp_NI80']].to_csv(HERE/'final_pilot/NI_sample_size_measured.csv',index=False)
    text += ['### Pointwise one-pp noninferiority at 80% power, true gap zero', '',
             'Illustrative use of B−P10 variance, not a measured variance for the untested proposal. '
             'Effective independent pairs; repeat/cell/candidate multiplicity can increase the episode count.', '',
             md(['Cell','Planning variance','Required effective pairs'],
                [[LABEL[r.cell],f'{r.variance_for_planning:.4f}',r.effective_pairs_1pp_NI80] for _,r in ni.iterrows()])]
    text += ['## 4. Post-hoc closed-loop evidence', '',
             'Same 500 task/init pairs per arm. Three reference replicates are averaged within init before uncertainty calculation. '
             'These pointwise intervals do not constitute the preregistered 64-test family.', '',
             '### A/B three-replicate result','',md(['Cell','A SR@IR','B SR@IR','B−A [95%], pp'],
                [[LABEL[c],f'{ab.loc[c,"A_mean"]:.3f}@{ab.loc[c,"A_IR"]:.3f}',
                  f'{ab.loc[c,"B_mean"]:.3f}@{ab.loc[c,"B_IR"]:.3f}',interval(ab.loc[c],'lo95','hi95','delta')] for c in CELLS])]
    for kind in ('guard_loo','direct_PCA'):
        d=abl[abl.kind.eq(kind)]
        text += ['### '+kind,'',md(['Cell','Removed guard / key variant','SR@IR','Difference from reference [95%], pp','Difference from A, pp'],
            [[LABEL[r.cell],r.disabled_guard if kind=='guard_loo' else 'direct PCA',f'{r.sr:.3f}@{r.IR:.3f}',
              interval(r,'lo95','hi95','delta'),f'{100*r.delta_A:+.2f}'] for _,r in d.iterrows()])]
    text += ['### Completed frontier snapshot (18 arms)', '',
             md(['Arm','SR@IR','P10 SR','Difference from P10 [95%], pp','Paired McNemar p'],
             [[r.arm,f'{r.sr:.3f}@{r.IR:.3f}',f'{r.P10_sr:.3f}',
               interval(r,'P10_lo95','P10_hi95','P10_delta'),f'{r.P10_p:.5g}'] for _,r in frontier.iterrows()])]
    (HERE/'FINAL_TABLES.md').write_text('\n'.join(text)+'\n')

    # A compact standalone figure with clearly separated inferential statuses.
    fig, axes=plt.subplots(1,2,figsize=(12,5.4),gridspec_kw={'width_ratios':[1.3,1]})
    y=np.arange(8)
    for i,c in enumerate(CELLS):
        r=primary[primary.cell.eq(c)&primary.contrast.eq('factorial_call')].iloc[0]
        axes[0].errorbar(100*r.estimate,i,xerr=np.array([[100*(r.estimate-r.lo_primary)],[100*(r.hi_primary-r.estimate)]]),
                         fmt='o',color='#245584',capsize=3)
    axes[0].set_yticks(y,[LABEL[c] for c in CELLS]);axes[0].invert_yaxis()
    axes[0].set_title('Preregistered: randomized CALL package\n64-contrast simultaneous intervals',fontsize=11)
    axes[0].set_xlabel('SR effect (percentage points)')
    d=abl[abl.disabled_guard.eq('no_progress')].set_index('cell')
    small=[c for c in CELLS if c.endswith('_50')]
    for i,c in enumerate(small):
        r=d.loc[c]
        axes[1].errorbar(100*r.delta,i,xerr=np.array([[100*(r.delta-r.lo95)],[100*(r.hi95-r.delta)]]),
                         fmt='o',color='#a64726',capsize=3)
    axes[1].set_yticks(np.arange(4),[LABEL[c] for c in small]);axes[1].invert_yaxis()
    axes[1].set_title('Post-hoc: remove no-progress package\nPointwise 95% intervals vs B mean',fontsize=11)
    axes[1].set_xlabel('SR effect of removal (percentage points)')
    for ax in axes:
        ax.axvline(0,color='gray',lw=.8);ax.grid(axis='x',alpha=.18);ax.spines[['top','right']].set_visible(False)
    fig.tight_layout()
    fig.savefig(HERE/'FINAL_evidence.png',dpi=180)
    fig.savefig(HERE/'FINAL_evidence.pdf')
    plt.close(fig)

    # Check component projections recover current fixed-task sandwich where all
    # 20 clusters are present. This also checks covariance of enrichment scores.
    checked=0
    for _,r in primary.iterrows():
        if r.status!='estimated' or r.clusters!=20:continue
        p=plans[plans.cell.eq(r.cell)&plans.contrast.eq(r.contrast)&plans.stage.eq('pilot')&plans.split.eq('all')].iloc[0]
        assert np.isclose(p.se_raw_covariance,r.se,rtol=1e-10,atol=1e-12),(r.cell,r.contrast,p.se_raw_covariance,r.se)
        checked+=1
    def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
    assert sha(HERE/'analyze_pilot.py')=='d2b040c94d84af22f40259c304cbccf3ba2bfad6aeb9c48ae8dbda0bffd67a2c'
    assert sha(HERE/'PREREG_FROZEN.md')=='61b2e5696ec95e7e767d8e6ad87d3e4ed1ef67494b85e1d6bed5c22b199bfb13'
    audits={
        'frozen_analyzer_unchanged':True,'frozen_preregistration_unchanged':True,
        'raw_component_SE_matches_frozen_sandwich_for_all_20_cluster_estimable_contrasts':checked,
        'primary_count':len(primary),'primary_simultaneous_excludes_zero':int(((primary.lo_primary>0)|(primary.hi_primary<0)).sum()),
        'table_sha256':sha(HERE/'FINAL_TABLES.md'),
        'source_scripts_sha256':{p.name:sha(p) for p in [HERE/'final_pilot.py',HERE/'final_exploratory.py',Path(__file__)]},
        'no_serving_controller_implemented':True,
    }
    (HERE/'final_delivery.json').write_text(json.dumps(audits,indent=2)+'\n')
    print(json.dumps(audits))


if __name__=='__main__':main()
