"""Summaries, episode-cluster intervals, and explicitly noncausal frozen-path reach."""
from analyze import *
from scipy.stats import norm

def interval(v,scale=1):
 return f"{v['mean']*scale:.3f} [{v['ci95'][0]*scale:.3f}, {v['ci95'][1]*scale:.3f}]"

def main():
 summary={};lines=['# Computed tables (generated by summarize.py)','', 'All intervals pointwise 95%, unless explicitly labeled family-18.','', '## Library LOEO conditional on frozen representation','', '| Cell | Rows/episodes | Head error | Actual ten-control error | Coverage AUC | Disagreement AUC | Event AUC |','|---|---:|---|---|---|---|---|']
 for cell in PAIRS:
  cal=json.loads((OUT/f'calibration_{cell}.json').read_text());lib=np.load(TMP/f'library_{cell}.npz');ep=cal['episode_stats'];st={}
  for k in ['error','error10','distance_auc','state_distance_auc','disagreement_auc','event_soon_auc','mode_switch_soon_auc','stall_auc']:
   st[k]=ci_mean([r[k] for r in ep if np.isfinite(r[k])])
  summary[cell]={'loeo':st,'calibration':{}}
  lines.append(f"| {cell} | {cal['rows']}/{cal['episodes']} | {interval(st['error'])} | {interval(st['error10'])} | {interval(st['distance_auc'])} | {interval(st['disagreement_auc'])} | {interval(st['event_soon_auc'])} |")
  # Freeze one threshold recipe before examining its reach: successful-episode max of joint risk, q90 higher.
  # This is finite-library calibration; no claim of conformal validity under frozen full-library representation.
  a=libload(cell);thresholds={};pooled_maxima=[];pooled_risk=[];both_maxima=[];both_risk=[]
  for t,tab in cal['tables'].items():
   rr=np.flatnonzero(lib['task']==int(t));risk=np.maximum(lib['distance'][rr]/tab['distance'][2],lib['disagreement'][rr]/tab['disagreement'][2])
   eligible=(a['step'][rr]>0)&(a['step'][rr]%2==0)
   maxima=[risk[(lib['episode'][rr]==eid)&eligible].max() for eid in np.unique(lib['episode'][rr]) if bool(lib['success'][rr[lib['episode'][rr]==eid][0]]) and np.any((lib['episode'][rr]==eid)&eligible)]
   pooled_maxima.extend(maxima);pooled_risk.extend(risk[eligible].tolist())
   br=np.minimum(lib['distance'][rr]/tab['distance'][2],lib['disagreement'][rr]/tab['disagreement'][2]);both_risk.extend(br[eligible].tolist())
   both_maxima.extend([br[(lib['episode'][rr]==eid)&eligible].max() for eid in np.unique(lib['episode'][rr]) if bool(lib['success'][rr[lib['episode'][rr]==eid][0]]) and np.any((lib['episode'][rr]==eid)&eligible)])
   summary[cell]['calibration'][t]=dict(successful_episodes=len(maxima),median_length=tab['median_length'])
  tau=float(np.quantile(pooled_maxima,.9,method='higher'));ret=float(np.quantile(pooled_risk,.5,method='higher'))
  for t in cal['tables']:thresholds[t]=tau;summary[cell]['calibration'][t].update(threshold=tau,return_threshold=ret)
  summary[cell]['pooled_calibration']=dict(successful_episodes=len(pooled_maxima),threshold=tau,return_threshold=ret,within_library_alert_fraction=float(np.mean(np.array(pooled_maxima)>tau)))
  # Conservative conjunction uses the SAME max-score threshold as the OR screen;
  # this makes its alert set a strict subset without retuning to outcome or reach.
  both_tau=max(1.,tau)
  summary[cell]['pooled_calibration'].update(both_threshold=both_tau,both_return_threshold=float(np.quantile(both_risk,.5,method='higher')),both_within_library_alert_fraction=float(np.mean(np.array(both_maxima)>both_tau)))
  A=read_arm(*PAIRS[cell][0]);replay=[]
  # Only A real anchors. Disagreement from cached top-five, scaled with the deployed library.
  for key,e in sorted(A['episodes'].items()):
   t=str(key[0]);tab=cal['tables'][t];fires=[];bfires=[];anchors=0
   for d in e['ds']:
    if not d.get('vision',True) or d['step']==0:continue
    ex=d.get('extras') or {}
    if 'd1' not in ex:continue
    anchors+=1;rows=(d.get('rows') or d['topk'])[:5];hh=np.asarray(a['action'][rows,:5,:7],float)/a['sigma'];disp=np.mean([np.sqrt(np.mean((hh[i]-hh[j])**2)) for i in range(len(hh)) for j in range(i+1,len(hh))])
    risk=max(ex['d1']/tab['distance'][2],disp/tab['disagreement'][2])
    if risk>thresholds[t]:fires.append(d['step'])
    if min(ex['d1']/tab['distance'][2],disp/tab['disagreement'][2])>both_tau:bfires.append(d['step'])
   replay.append(dict(task=key[0],init=key[1],first=fires[0] if fires else None,first_both=bfires[0] if bfires else None,alerts=len(fires),anchors=anchors,success=e['success']))
  p=json.loads((OUT/f'paired_{cell}.json').read_text());by={(r['task'],r['init']):r for r in p['records']}
  for r in replay:
   b=by[r['task'],r['init']];r['paired_delta']=b['delta'];r['B_first_miss']=b['first_miss']
   r['before_B_first_miss']=r['first'] is not None and (b['first_miss'] is None or r['first']<b['first_miss'])
   r['both_before_B_first_miss']=r['first_both'] is not None and (b['first_miss'] is None or r['first_both']<b['first_miss'])
  reach=dict(episodes=len(replay),flagged=sum(r['first'] is not None for r in replay),flagged_success=sum(r['first'] is not None and r['success'] for r in replay),before_B_first_miss=sum(r['before_B_first_miss'] for r in replay),rows=replay,thresholds=thresholds)
  reach['configuration_delta_split']=group_delta([r['paired_delta'] for r in replay],[r['first'] is not None for r in replay]);summary[cell]['replay']=reach
  reach['both_flagged']=sum(r['first_both'] is not None for r in replay);reach['both_success_flagged']=sum(r['first_both'] is not None and r['success'] for r in replay);reach['both_before_B_first_miss']=sum(r['both_before_B_first_miss'] for r in replay)
  summary[cell]['paired']={k:v for k,v in p.items() if k not in ['records','guards','examples','sources']}
  bo=[r for r in p['records'] if r['delta']==1];fm=[r for r in bo if r['first_miss'] is not None];bm=[r for r in p['records'] if r['first_miss'] is not None]
  summary[cell]['B_only_timing']=dict(B_only=len(bo),with_call=len(fm),state_divergence_before_or_at=sum(r['state_divergence'] is not None and r['state_divergence']<=r['first_miss'] for r in fm),action_divergence_before=sum(r['action_divergence'] is not None and r['action_divergence']<r['first_miss'] for r in fm),first_miss_steps=np.quantile([r['first_miss'] for r in fm],[.25,.5,.75]).tolist(),first_phase=np.quantile([r['first_miss_features']['phase'] for r in fm],[.25,.5,.75]).tolist(),first_reasons=dict(collections.Counter(r['first_miss_features']['reason'] for r in fm)),policy_cache_rms=np.quantile([r['first_miss_features']['policy_cache_rms'] for r in fm],[.25,.5,.75]).tolist())
  gg={};allcalls=[c for r in p['records'] for c in r['calls']]
  for reason,rr in p['guards'].items():
   calls=[c for r in rr for c in r['calls']];after=[c for c in calls if c['next_phase_gain'] is not None]
   gg[reason]=dict(episodes=len(rr),successes=sum(r['success'] for r in rr),calls=len(calls),B_only=sum(r['paired_delta']==1 for r in rr),A_only=sum(r['paired_delta']==-1 for r in rr),success_rate=ci_mean([r['success'] for r in rr]),call_weighted_next_phase_gain=np.mean([c['next_phase_gain'] for c in after]) if after else None,next_anchor_policy_fraction=np.mean([c['next_is_policy'] for c in after]) if after else None)
  summary[cell]['guards']=gg
  summary[cell]['call_distribution']=dict(calls=len(allcalls),calls_failed=sum(not c['success'] for c in allcalls),terminal=sum(c['terminal_call'] for c in allcalls),episodes_any_call=len(bm),first_call_success_rate=ci_mean([r['B_success'] for r in bm]),calls_early=sum(c['phase']<.5 for c in allcalls),calls_late=sum(c['phase']>=.5 for c in allcalls),median_per_success=float(np.median([r['M'] for r in p['records'] if r['B_success']])),median_per_failure=float(np.median([r['M'] for r in p['records'] if not r['B_success']])))
  # Deterministic example: lowest (task, init) B-only episode with a first MISS and separation later.
  examples=[r for r in p['examples'] if r['state_divergence'] is None or r['state_divergence']>r['first_miss']]
  summary[cell]['example']=examples[0] if examples else None

 lines+=['','## Paired configuration contrasts','', '| Cell | A SR/IR | B SR/IR | B−A pp [95%] | B-only/A-only | Extra calls/ep | Gain pp/call [95%] |','|---|---|---|---|---|---|---|']
 for c,s in summary.items():
  p=s['paired'];ratio=p['configuration_gain_per_added_call'];v=dict(mean=ratio['value'],ci95=ratio['ci95'])
  lines.append(f"| {c} | {p['A_SR']:.3f}/{p['A_IR']:.5f} | {p['B_SR']:.3f}/{p['B_IR']:.5f} | {interval(p['contrast'],100)} | {p['B_only']}/{p['A_only']} | {p['B_M_per_episode']:.3f} | {interval(v,100)} |")
 lines+=['','## B-only episode timing','', '| Cell | B-only with MISS / total | State separation before/at first MISS | First MISS slot q25/50/75 | First matched phase q25/50/75 | First reason counts |','|---|---|---|---|---|---|']
 for c,s in summary.items():
  r=s['B_only_timing'];lines.append(f"| {c} | {r['with_call']}/{r['B_only']} | {r['state_divergence_before_or_at']} | {r['first_miss_steps']} | {np.round(r['first_phase'],3).tolist()} | {r['first_reasons']} |")
 lines+=['','## Frozen A-path reach of proposed threshold (not a rollout prediction)','', '| Cell | Flagged / 500 | Successful A episodes flagged | Before B first MISS | Threshold range |','|---|---|---|---|---|']
 for c,s in summary.items():
  r=s['replay'];vs=list(r['thresholds'].values());lines.append(f"| {c} | {r['flagged']} | {r['flagged_success']} | {r['before_B_first_miss']} | {min(vs):.3f}–{max(vs):.3f} |")
 lines+=['','## Conjunction candidate (coverage AND disagreement)','', '| Cell | Threshold | Flagged /500 | Successful A flagged | Before B first MISS |','|---|---|---|---|---|']
 for c,s in summary.items():
  r=s['replay'];lines.append(f"| {c} | {s['pooled_calibration']['both_threshold']:.4f} | {r['both_flagged']} | {r['both_success_flagged']} | {r['both_before_B_first_miss']} |")
 lines+=['','## Paired benefit heterogeneity at library-clock quarter landmark','', '| Cell / signal | High n | B−A high pp | B−A low pp | Interaction pp [95%] |','|---|---|---|---|---|']
 for c,s in summary.items():
  for k,v in s['paired']['landmark_interactions'].items():
   if 'interaction' not in v:continue
   ss=dict(mean=v['interaction'],ci95=v['interaction_ci95']);lines.append(f"| {c} / {k} | {v['n_high']} | {100*v['high']['mean']:.2f} | {100*v['low']['mean']:.2f} | {interval(ss,100)} |")
 # Causal family-wise sensitivity recomputed from saved raw-audited episode records.
 from exp.offline_search.rounds.r04.k5_rand.estimate import cluster_draws,effect
 causal={}
 for n in (50,500):
  x=json.loads((OUT/f'causal_{n}.json').read_text());rows=x['features'];cid,w=cluster_draws(rows,4000,SEED);expo=np.array([r['exposed'] for r in rows]);cs={}
  for feature,v in x['subgroups'].items():
   if 'threshold' not in v:continue
   vals=np.array([r.get('features',{}).get(feature,np.nan) for r in rows],float);ok=expo&np.isfinite(vals)
   hi,hd=effect(rows,ok&(vals>=v['threshold']),cid,w);lo,ld=effect(rows,ok&(vals<v['threshold']),cid,w)
   if hd is None or ld is None:continue
   delta=hi['delta']['Y']-lo['delta']['Y'];se=np.nanstd(hd[:,0]-ld[:,0],ddof=1);z=norm.ppf(1-.05/(2*18));v['family18_normal_ci']=[delta-z*se,delta+z*se];cs[feature]=v
  lm=np.array([r['landmark_class'] for r in rows]);one,od=effect(rows,lm==1,cid,w);three,td=effect(rows,lm==3,cid,w)
  causal[n]=dict(ITT=x['ITT'],subgroups=x['subgroups'],multiplicity=cs,first_minus_third=dict(value=one['delta']['Y']-three['delta']['Y'],ci95=np.quantile(od[:,0]-td[:,0],[.025,.975]).tolist()),pre_guard_exposures=x['pre_guard_exposures'])
 lines+=['','## Causal K5 feature interactions','', '| Scale / feature | Exposed high/low | CALL−CACHE high pp | CALL−CACHE low pp | Interaction pp [95%] | Family-18 normal interval pp |','|---|---|---|---|---|---|']
 for n,cs in causal.items():
  for k,v in cs['multiplicity'].items():
   vi=dict(mean=v['interaction'],ci95=v['interaction_ci95']);lines.append(f"| {n} / {k} | {v['high']['n']}/{v['low']['n']} | {100*v['high']['delta']['Y']:.2f} | {100*v['low']['delta']['Y']:.2f} | {interval(vi,100)} | {np.round(np.array(v['family18_normal_ci'])*100,2).tolist()} |")
 # Existing cross-controller failure proxy is a falsification check, not a new fitted predictor.
 old=json.loads(Path('exp/offline_search/rounds/r05/ideation_B/log_results.json').read_text());external={}
 for scale,r in old['risk_lda'].items():
  z=r['external'];rho=spearmanr([i['failure'] for i in z],[i['predicted_failure'] for i in z])
  external[scale]=dict(arms=len(z),spearman=float(rho.statistic),p=float(rho.pvalue),rows=z,LOTO_AUC=r['LOTO_AUC'])
 dump('summary.json',dict(cells=summary,causal=causal,prior_external_risk=external));(OUT/'TABLES.md').write_text('\n'.join(lines)+'\n')
 print('Wrote summary.json and TABLES.md',flush=True)

if __name__=='__main__':main()
