"""Collect observed JSON results, assert completeness, and write the numerical hand-back tables."""
import hashlib
import json
from pathlib import Path

import numpy as np

from exp.offline_search.rounds.r06.p2_ablations.make_arms import HERE, RUN


def read(p):
    return json.loads(p.read_text())


def main():
    metric = sorted([read(p) for p in (HERE / 'results').glob('r6p2_identity_*_metric.json')], key=lambda r:r['arm'])
    audits = sorted([read(p) for p in (RUN / 'replay').glob('audit_*/audit.json') if p.parent.name != 'audit_smoke'],
                    key=lambda r:(r['model'], r['suite'], r['stream']))
    nesting = sorted([read(p) for p in (RUN / 'replay').glob('nesting_*/nesting.json')], key=lambda r:(r['model'],r['suite']))
    allvision = sorted([read(p) for p in (HERE / 'results').glob('allvision_*.json')], key=lambda r:(r['model'],r['suite']))
    validation, logic = read(HERE / 'results/validation.json'), read(HERE / 'results/logic.json')
    assert [len(metric), len(audits), len(nesting), len(allvision)] == [8, 8, 4, 4]
    assert all(x['PASS'] for x in metric + audits + nesting + allvision + [validation, logic])
    smokes = []
    for p in sorted((RUN / 'replay').glob('smoke_*/report.json')):
        r = read(p)
        data = np.load(p.parent / 'served.npz')
        records = [json.loads(s) for s in (p.parent / 'decisions_smoke.jsonl').read_text().splitlines() if '"ev": "dec"' in s]
        assert len(records) == r['decisions']
        assert r['stage1_calls'] == r['vision'] and r['max_blind_run'] == 1
        tails = 0
        for i, d in enumerate(records):
            if not d['hit']:
                assert d['extras']['os_force_miss'] == 1 and d['src'] == 'policy'
                if i + 1 < len(records) and records[i+1]['step'] != 0:
                    assert records[i+1]['src'] == 'policy_tail'
                    assert np.array_equal(data['served'][i+1, :5], data['served'][i, 5:10])
                    tails += 1
            if d.get('src') == 'cache_blind':
                assert np.array_equal(data['served'][i, :5, :7], data['served'][i-1, 5:10, :7])
        if 'IdentityBlindAWM' in r['spec']:
            assert r['misses'] == 0
        r['asserted_policy_tails'] = tails
        smokes.append(r)
    assert len(smokes) == 24
    result = dict(PASS=True, metric=metric, matched_history_audits=audits, nesting=nesting, allvision=allvision,
                  plugin_smokes=smokes, logic=logic,
                  totals=dict(metric_queries=sum(x['queries'] for x in metric),
                              audit_vision_queries=sum(x['baseline']['vision_queries'] for x in audits),
                              audit_decisions=sum(read(p.parent / 'report.json')['decisions']
                                                  for p in (RUN / 'replay').glob('audit_*/audit.json')
                                                  if p.parent.name != 'audit_smoke'),
                              allvision_queries=sum(x['queries'] for x in allvision),
                              nesting_decisions=sum(x['counts']['anchors']+x['counts']['blind_tails'] for x in nesting),
                              smoke_decisions=sum(x['decisions'] for x in smokes)))
    (HERE / 'results/summary.json').write_text(json.dumps(result, indent=1)+'\n')
    lines = ['## Observed numerical results', '', 'All tables below are generated by `summarize.py` from saved reports.', '',
             '### Exact identity metric', '', '| arm | queries | early / main | ordered top-16 mismatches | max distance error |',
             '|---|---:|---:|---:|---:|']
    for r in metric:
        c=r['counts']
        lines.append(f"| {r['arm']} | {r['queries']} | {c['cache_early']+c['inf_early']} / {c['cache_main']+c['inf_main']} | {r['exact_ordered_top16_mismatches']} | {r['max_selected_distance_absolute_error']:.3g} |")
    lines += ['', '### Same-history B replay: MISS decisions removed', '',
              'Each row is a 50-episode-library cell, replayed on all 500 recorded episodes of each stream. Counts are direct verdict changes on B histories, not rollout effects.', '',
              '| model / suite / stream | decisions | vision anchors | B MISS | −stuck | −terminal | −overtime | −no-progress | overtime kept by −stuck |',
              '|---|---:|---:|---:|---:|---:|---:|---:|---:|']
    for r in audits:
        report=read(RUN/'replay'/f"audit_{r['model']}_{r['suite']}_{r['stream']}"/'report.json')
        v=r['variants']
        lines.append(f"| {r['model']} / {r['suite']} / {r['stream']} | {report['decisions']} | {r['baseline']['vision_queries']} | {r['baseline']['baseline_misses']} | "+' | '.join(str(v[g]['removed_misses']) for g in ('stuck','terminal','overtime','no_progress'))+f" | {v['stuck']['overtime_fires_retained']} |")
    lines += ['', 'Every checked result had identical top-k, scores, action, confidence and non-verdict extras. `os_flags` drops the selected bit, `os_reason` becomes the lowest remaining bit, and the force-MISS verdict changes iff that bit was the only firing reason. A reason code can change while MISS remains true when multiple guards fire.', '',
              '### New all-off path nesting (50-episode libraries, all 500 cache-stream episodes)', '',
              '| model / suite | anchors | blind tails | new off == original B-off | stable-tie A equal | deployed-A tied anchors / tails |',
              '|---|---:|---:|---|---|---:|']
    for r in nesting:
        c=r['counts']
        lines.append(f"| {r['model']} / {r['suite']} | {c['anchors']} | {c['blind_tails']} | exact | exact | {c.get('deployed_A_tied_anchors',0)} / {c.get('deployed_A_tied_tails',0)} |")
    lines += ['', '### Additional checks', '',
              f"- All-vision branch: {result['totals']['allvision_queries']:,} recorded queries over 240 episodes; zero mismatches.",
              f"- All 24 installed-plugin smokes passed on three recorded episodes per arm ({result['totals']['smoke_decisions']:,} decisions). Cache tails and each nonfinal policy MISS tail were checked against rows 5..9 of its source chunk. No metric-arm MISS; at most one blind decision in a row.",
              f"- Logic tests: {logic['bitmask_cases']} bitmask cases, {logic['refusals']} refusal cases, {logic['explicit_progress_veto_cases']} explicit blind-veto cases.",
              '- Emitter, cache-config parser, plugin parser, exact source-field preservation, and fit metadata: 24/24.', '',
              '### Prefit artifacts', '', f'Root: `{RUN}/fits/`. Every file was freshly fitted with the stock plugin prefit entry point.', '',
              '| file | bytes | SHA256 |', '|---|---:|---|']
    for r in validation['artifacts']:
        lines.append(f"| {Path(r['path']).name} | {r['bytes']} | `{r['sha256']}` |")
    (HERE / 'results/TABLES.md').write_text('\n'.join(lines)+'\n')
    hashes=[]
    for p in sorted(HERE.rglob('*')):
        if p.is_file() and p.name != 'files.sha256':
            hashes.append(f'{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.relative_to(HERE)}\n')
    (HERE / 'results/files.sha256').write_text(''.join(hashes))
    print(json.dumps(result['totals']), flush=True)


if __name__ == '__main__':
    main()
