#!/bin/bash
# start_server.sh <model pi05|groot> <suite libero_spatial|libero_10> <port> <yaml> <log-dir> <tag> [--os-* plugin args]
#
# One single-replica pure-cache server in tmux session oscl<port> (name unique to this line), pinned with taskset.
#   plugin arm : pass --os-method <spec> [--os-kwargs JSON] --os-cell <m>_<s>_cache [--os-log-inputs] ...
#   native arm : pass --os-method native --os-cell <m>_<s>_cache          (native retrieval, plugin logs only)
#   stock arm  : STOCK=1 and no --os-* args                                  (stock entry point, no plugin at all)
# --os-log-dir / --os-tag are filled in here (<log-dir>, <tag>).
# env: CPUS (default 34-37,78-81: the ONLY CPUs this line may use unless the coordinator says otherwise)
#      STAGE1_ONLY (default 1) stage 2/3 weights on the meta device: pure cache never runs them, a MISS would fail
#                   loudly. Verified: identical keys; GPU per server pi05 7.6 -> 2.2 GB, GR00T 5.7 -> 1.9 GB. 0 = full model
#      OMP (default 4) torch intra-op threads (OMP/MKL); numpy's OpenBLAS is always pinned to 1 thread
#      (OPENBLAS_NUM_THREADS=1, as the harness workers) so online method outputs are bit-identical to offline
#      GPU_LOCK (default 0 = OPENPI_SERVER_GPU_MEMORY_LOCK off: freed memory is released on connection close)
# Writes <log-dir>/server_<tag>.log (ends with SERVER_EXIT=<rc>), <log-dir>/server_<tag>.pid, <log-dir>/launch_<tag>.sh.
set -u
MODEL=${1:?model}; SUITE=${2:?suite}; PORT=${3:?port}; YAML=${4:?yaml}; LOGD=${5:?log-dir}; TAG=${6:?tag}; shift 6
R=/home/weiland/projects/openpi
G=/home/weiland/projects/openpi_ext/third_party/gr00t_n15
CPUS=${CPUS:-34-37,78-81}
OMP=${OMP:-4}
S1=${STAGE1_ONLY:-1}
STOCK=${STOCK:-0}
SESSION=oscl$PORT
mkdir -p "$LOGD"
LOG=$LOGD/server_$TAG.log
# rotate a previous run's log so the chain's boot check (greps SERVER_EXIT= / Error) only sees this launch
[ -f "$LOG" ] && mv "$LOG" "$LOG.prev.$(date +%s)"
PIDF=$LOGD/server_$TAG.pid
LAUNCH=$LOGD/launch_$TAG.sh
tmux has-session -t "$SESSION" 2>/dev/null && { echo "tmux $SESSION exists"; exit 2; }
ss -ltnH "sport = :$PORT" | grep -q . && { echo "port $PORT busy"; exit 2; }
[ -f "$YAML" ] || { echo "yaml $YAML missing"; exit 2; }

PLUG=()
if [ "$STOCK" != "1" ]; then
  PLUG=("$@" --os-log-dir "$LOGD" --os-tag "$TAG")
elif [ $# -gt 0 ]; then
  echo "STOCK=1 takes no plugin args"; exit 2
fi

case "$MODEL" in
  pi05)
    PY=$R/.venv/bin/python
    ENTRY=$R/exp/offline_search/closed_loop/serve_pi05.py
    [ "$STOCK" = "1" ] && ENTRY=$R/scripts/serve_policy.py
    EXTRA=()
    [ "$S1" = "1" ] && EXTRA=(--stage1-device cuda:0 --stage2-device meta --stage3-device meta)
    ARGS=("${PLUG[@]}" --port "$PORT" --replicas 1 --cache-config "$YAML" "${EXTRA[@]}"
          policy:checkpoint --policy.config pi05_libero
          --policy.dir /home/weiland/.cache/openpi/openpi-assets/checkpoints/pi05_libero_pytorch)
    ENVS="export PYTHONPATH=$R:$R/src"
    ;;
  groot)
    PY=/home/weiland/projects/openpi_ext/envs/gr00t_n15_venv/.venv/bin/python
    ENTRY=$R/exp/offline_search/closed_loop/serve_groot.py
    [ "$STOCK" = "1" ] && ENTRY=$R/exp/libero_groot/serve_groot_libero.py
    case "$SUITE" in libero_spatial) CKPT=/data/ckpt/n15_libero_spatial ;; libero_10) CKPT=/data/ckpt/n15_libero_10 ;;
      *) echo "bad suite $SUITE"; exit 2 ;; esac
    EXTRA=()
    [ "$S1" = "1" ] && EXTRA=(--stage1-only)
    ARGS=("${PLUG[@]}" --checkpoint "$CKPT" --port "$PORT" --denoising-steps 8 --concurrent --allow-dynamic-bundles
          --cache-config "$YAML" "${EXTRA[@]}")
    ENVS="export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 OPENPI_MONITOR_LEVEL=BASIC PYTHONPATH=$G:$G/examples/Libero:$R:$R/src:$R/packages/openpi-client/src"
    ;;
  *) echo "bad model $MODEL"; exit 2 ;;
esac

{
  echo "#!/bin/bash"
  echo "# generated by start_server.sh $(date -Is)"
  echo "cd $R"
  echo "export HOME=/home/weiland OMP_NUM_THREADS=$OMP MKL_NUM_THREADS=$OMP OPENBLAS_NUM_THREADS=1 OPENPI_SERVER_GPU_MEMORY_LOCK=${GPU_LOCK:-0}"
  echo "$ENVS"
  printf 'taskset -c %q %q %q' "$CPUS" "$PY" "$ENTRY"
  printf ' %q' "${ARGS[@]}"
  printf ' >> %q 2>&1 &\n' "$LOG"
  echo "echo \$! > $PIDF"
  echo "wait \$!"
  echo "echo SERVER_EXIT=\$? >> $LOG"
} > "$LAUNCH"
chmod +x "$LAUNCH"
printf '%s\n%s\n' "$PORT" "$YAML" > "$LOGD/server_$TAG.meta"
echo "START $(date -Is) model=$MODEL suite=$SUITE port=$PORT tag=$TAG cpus=$CPUS stage1_only=$S1 stock=$STOCK" >> "$LOG"
tmux new -s "$SESSION" -d "bash $LAUNCH"
echo "started $SESSION log=$LOG"
