#!/usr/bin/env bash
# GR00T B prefits (RUN defaults to the r06 paper run root). Refuses existing artifacts.
set -euo pipefail
cd /home/weiland/projects/openpi
RUN=${RUN:-/home/weiland/trace_runs/os_closed_loop/r06_paper}
mkdir -p "$RUN/fits" "$RUN/prefit_logs"
pids=()
taskset -c 26-29,70-73 env OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 CUDA_VISIBLE_DEVICES= PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=.:src .venv/bin/python -m exp.offline_search.closed_loop.plugin --os-method exp.offline_search.rounds.r06.p1_groot_commit.judge:GrootCommitJudge --os-kwargs '{"base_kwargs":{"lib":"current","kref":5,"serving":"anchor_tail","budget":1,"gates":"budget_only"},"progress_guard":"noprog_span","events":"none","stuck_guard":"vision_confirmed","policy_tail_gate":"lifecycle","monitor":"off"}' --os-cell groot_l10_cache --os-root /home/weiland/trace_runs/offline_search_store --os-log-dir $RUN/prefit_logs/r6p1_c10_g_l10_50 --os-tag r6p1_c10_g_l10_50 --os-blind --os-policy-tail --os-policy-tail-blocks 1 --os-judge guard_only --os-no-shadow-native --os-fit-artifact $RUN/fits/r6p1_c10_g_l10_50.pkl > "$RUN/fits/r6p1_c10_g_l10_50.prefit.log" 2>&1 & pids+=($!)
taskset -c 26-29,70-73 env OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 CUDA_VISIBLE_DEVICES= PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=.:src .venv/bin/python -m exp.offline_search.closed_loop.plugin --os-method exp.offline_search.rounds.r06.p1_groot_commit.judge:GrootCommitJudge --os-kwargs '{"base_kwargs":{"lib":"big","kref":8,"serving":"anchor_tail","budget":1,"gates":"budget_only"},"progress_guard":"noprog_span","events":"none","stuck_guard":"vision_confirmed","policy_tail_gate":"lifecycle","monitor":"off"}' --os-cell groot_l10_cache --os-root /home/weiland/trace_runs/offline_search_store --os-log-dir $RUN/prefit_logs/r6p1_c10_g_l10_500 --os-tag r6p1_c10_g_l10_500 --os-blind --os-policy-tail --os-policy-tail-blocks 1 --os-judge guard_only --os-no-shadow-native --os-fit-artifact $RUN/fits/r6p1_c10_g_l10_500.pkl > "$RUN/fits/r6p1_c10_g_l10_500.prefit.log" 2>&1 & pids+=($!)
taskset -c 26-29,70-73 env OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 CUDA_VISIBLE_DEVICES= PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=.:src .venv/bin/python -m exp.offline_search.closed_loop.plugin --os-method exp.offline_search.rounds.r06.p1_groot_commit.judge:GrootCommitJudge --os-kwargs '{"base_kwargs":{"lib":"current","kref":5,"serving":"anchor_tail","budget":1,"gates":"budget_only"},"progress_guard":"noprog_span","events":"none","stuck_guard":"vision_confirmed","policy_tail_gate":"lifecycle","monitor":"off"}' --os-cell groot_spatial_cache --os-root /home/weiland/trace_runs/offline_search_store --os-log-dir $RUN/prefit_logs/r6p1_c10_g_sp_50 --os-tag r6p1_c10_g_sp_50 --os-blind --os-policy-tail --os-policy-tail-blocks 1 --os-judge guard_only --os-no-shadow-native --os-fit-artifact $RUN/fits/r6p1_c10_g_sp_50.pkl > "$RUN/fits/r6p1_c10_g_sp_50.prefit.log" 2>&1 & pids+=($!)
taskset -c 26-29,70-73 env OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 CUDA_VISIBLE_DEVICES= PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=.:src .venv/bin/python -m exp.offline_search.closed_loop.plugin --os-method exp.offline_search.rounds.r06.p1_groot_commit.judge:GrootCommitJudge --os-kwargs '{"base_kwargs":{"lib":"big","kref":8,"serving":"anchor_tail","budget":1,"gates":"budget_only"},"progress_guard":"noprog_span","events":"none","stuck_guard":"vision_confirmed","policy_tail_gate":"lifecycle","monitor":"off"}' --os-cell groot_spatial_cache --os-root /home/weiland/trace_runs/offline_search_store --os-log-dir $RUN/prefit_logs/r6p1_c10_g_sp_500 --os-tag r6p1_c10_g_sp_500 --os-blind --os-policy-tail --os-policy-tail-blocks 1 --os-judge guard_only --os-no-shadow-native --os-fit-artifact $RUN/fits/r6p1_c10_g_sp_500.pkl > "$RUN/fits/r6p1_c10_g_sp_500.prefit.log" 2>&1 & pids+=($!)
for p in "${pids[@]}"; do wait "$p"; done
sha256sum "$RUN"/fits/r6p1_c10_g_*.pkl
